### ISSUE TITLE
List all open RFCs and order them by progression/stability.

### ISSUE THREAD

**Issue by martndemus** [emberjs/rfcs#103]
(We had a small discussion about this at EmberCamp.)

It would be nice to have a list of all current open (and recently landed in canary/beta/stable) RFCs with some kind of ranking/ordering on how far along the RFC process these RFCs are. Currently this is not easy to discern unless you pedantically keep up with every RFC opened.

I would like to propose we copy the way [TC39](https://github.com/tc39/ecma262) keeps track of their open RFCs. Although i'd like to have the stage numbers replaced with meaningful keywords.

My use case is that I try to follow RFCs to keep up with changes being made to Ember, as RFCs are currently the best source for this.

**Comment by rwjblue** [comment]
There is an open PR in the website repo regarding this. Can you take a look and see if it addresses everything here?

**Comment by martndemus** [comment]
Yes, that looks like something that would solve this issue. I will comment over there.

**Comment by WebCloud** [comment]
I could be useful to link it here

**Comment by martndemus** [comment]
🎉
