### ISSUE TITLE
Migrating to C++

### ISSUE THREAD

**Issue by IAmJulianAcosta** [emberjs/rfcs#104]
Hello, I do not know if this idea is beyond the scope of ember, or even if it is possible to implement, but I think it would be a big step for the development of Ember. 

This is abou migrating Ember to C++ for subsequent compilation to Javascript using asm.js.

The idea behind this is as follows:

Using Ember CLI to develop as usual, using Javascript, as has been done so far. Ember CLI, will compile that to C++ code, and then convert it to javascript using ASM, which is sent to the browser.

On the other hand, having an intermediate code in C ++, allows ember to run faster in hybrid applications, since you could run this code in iOS, and Android using JNI, which would make ember in the most appropriate tool for the development of native applications, due to its high performance, so minimal amount of javascript will be executed in mobile device, and all the logic will be executed in C++.

**Comment by taras** [comment]
It's a curious idea, but it's unlikely that you'll get much traction on this idea as is evident with lack of comments :)

**Comment by stefanpenner** [comment]
The scope of this seem pretty hefty for us to explore, with large risks and unknown wins. Unless someone with a large budget wants to invest in some exploration. (Although if someone can demonstrate value, who knows, but wouldn't bet on it)

Interesting and maybe related? is an attempt at an ES6 AOT compiler: https://github.com/toshok/echojs

I hate being a kill-joy, but the dynamism and complexity of JS likely make this a non-starter.

Our work towards a better performing ember are in the works [feel free to follow along here](https://github.com/tildeio/glimmer)

**Comment by stefanpenner** [comment]
If there are further ideas, or experiments the discussion can continue here. For now, this will be closed.
