### ISSUE TITLE
Have link-to helper and action cooperate by closing on transitions.

### ISSUE THREAD

**Issue by spectras** [emberjs/rfcs#105]
I have been looking around a lot and could not find anything, sorry if I just missed it.

Now we have the ability to create closure actions with the `{{action}}` helper and pass actions to be invoked by a component, it opens a wide array of possibilites. For instance, we can let a component display some data, and pass it a closure action it will trigger when the user clicks on something.

``` hbs
{{my-list data=library.books nameClicked=(action "selectBook") }}
```

``` hbs
<ul>{{#each books as |book|~}}
    <li><button {{action attrs.nameClicked book}}>{{book.name}}</button></li>
{{~/each}}</ul>
```

That example does not actually close over anything but the handler, but that is enough. This is very powerful when cascading sub-components, saving the hassle of forwarding actions on the way up.

I believe **it would be useful to allow passing a transition as an action this way**. That is:

``` hbs
{{my-list data=library.books nameClicked=(link-to 'library.book.edit' library) }}
```

Exact syntax could vary. Maybe it could even be another helper instead of `link-to`.

So, more to the point, I believe it would be useful to be able to build a callable action that, when triggered, will initiate a transition.
- Route name is mandatory.
- Additional link-to parameters are closed over (in the example, `library` is closed over).
- Parameters passed when sending the action are appended (in the example, `book` is appended, so transition will have both `library` and `book`).

This behavior can be obtained right now by making an action on the controller that invokes `transitionTo`, but that's a bit clumsy.

**Comment by mmun** [comment]
This seems like a great idea!

**Comment by locks** [comment]
This should be much more easily accomplished with the new public router service. I suggest hooking into that and releasing it as an addon.

**Comment by miguelcobain** [comment]
https://github.com/peec/ember-route-action

**Comment by vitch** [comment]
> the new public router service

@locks  - do you have some more information on that? I can find [an RFC](https://github.com/emberjs/rfcs/pull/95) but nothing more concrete.

**Comment by locks** [comment]
@vitch that it is. It is currently being implemented mainly by rwjblue. See https://github.com/rwjblue/ember.js/tree/router-service.

**Comment by locks** [comment]
The router service is now on [Ember 2.15 beta](https://github.com/emberjs/ember.js/blob/master/features.json#L8).
