### ISSUE TITLE
Make factory deprecation warnings more helpful

### ISSUE THREAD

**Issue by zacstewart** [emberjs/rfcs#111]
[This](https://github.com/emberjs/ember.js/blob/28163882e229719f496f5cbd72fdc7e84c9431b9/packages/ember-application/lib/utils/validate-type.js#L25) deprecation warning is difficult to understand, and easily improved. The following message provides some information, but not enough to fix the problem:

> Ember Inspector (Deprecation Trace): In Ember 2.0 service factories must have an `isServiceFactory` property set to true. You registered (subclass of Ember.ObjectProxy) as a service factory. Either add the `isServiceFactory` property to this factory or extend from Ember.Service.

In my case, I had to temporarily patch my copy of Ember to get it to tell me _which_ service was offending. It would be helpful to include `parsedName.fullName` in the message.

**Comment by rwjblue** [comment]
Yes, I agree that is less helpful than it could be.  The `(subclass of Ember.ObjectProxy)` part is the result of calling `factory.toString()`, but unfortunately that didn't really help narrow things down.

**Comment by locks** [comment]
I believe we have improved this since, can someone confirm?

**Comment by sandstrom** [comment]
@zacstewart Can we close this issue? I don't think it's relevant anymore

**Comment by zacstewart** [comment]
Yep.
