### ISSUE TITLE
Add waitFor(selector) test helper

### ISSUE THREAD

**Issue by kellyselden** [emberjs/rfcs#127]
Referred [here](https://github.com/emberjs/ember.js/issues/13025#issuecomment-192437264).

A `waitFor` helper would be useful for components that wrap jQuery plugins that take a while to generate their html. The problem is expanded [here](http://stackoverflow.com/questions/35686006/ember-component-how-to-wait-for-random-jquery-plugin-initialization). It could convert this:

``` js
let done = assert.async();

click('.button-to-show-component');

setTimeout(() => {
  andThen(function() {
    assert.strictEqual(find('.jquery-stuff').length, 1);
    done();
  });
}, 500);
```

to this:

``` js
click('.button-to-show-component');

waitFor('.jquery-stuff');

andThen(function() {
  assert.strictEqual(find('.jquery-stuff').length, 1);
});
```

It would have the same basic signature as the `find` helper. A basic implementation is [here](https://github.com/kellyselden/ember-datetimepicker/blob/d7de77fcdf163a897ad90088d84a451499dd3d9f/tests/helpers/wait-for.js), and it in action is [here](https://github.com/kellyselden/ember-datetimepicker/blob/d7de77fcdf163a897ad90088d84a451499dd3d9f/tests/acceptance/date-time-picker-test-test.js#L23).

**Comment by mmun** [comment]
I like this. I'd suggest making the API `this.waitFor({ selector: ... })` or even just `this.wait({ selector: ... })` as we will probably want to wait on other things in the future, e.g. ajax, routing, etc.

**Comment by kellyselden** [comment]
@mmun You could also do type sniffing, if arg is string else treat as object, but that makes the API a bit fragile.

**Comment by stefanpenner** [comment]
this type of sniffing (in our tests are work at-least) often result in quite brittle tests. Largely, because now a failure isn't attached to the action triggering, rather a lengthy timeout of sorts.

Maybe i just have PTSD, and it is ok when used in some scenarios, but I just felt i should mention my experience.

**Comment by rwjblue** [comment]
I also wanted to mention that 'this.wait' is almost certainly going to be provided by the new testing harness proposed in another RFC.

**Comment by kgish** [comment]
Also of interest:
http://discuss.emberjs.com/t/waituntil-async-helper-feedback/9444

**Comment by rwjblue** [comment]
`waitFor` (and `waitUntil`) is a public API since around Ember 3.0. Thanks for this discussion, it absolutely influenced that implementation.
