### ISSUE TITLE
Add {{array ...}} helper

### ISSUE THREAD

**Issue by kellyselden** [emberjs/rfcs#128]
It seems it would be a perfect companion to the {{hash ...}} helper:

``` hbs
{{hash
  name="parent"
  children=(array
    (hash
      name="child1"
    )
    (hash
      name="child2"
    )
  )
}}
```

It would probably get the most use in component integration tests, but could be useful in normal templates as well. Taken from [here](https://github.com/kellyselden/ember-array-helper).

**Comment by Serabe** [comment]
I created Ember pirate for that helper. It is the only addon that can work
without being installed :)

https://github.com/Serabe/ember-pirate

**Comment by mmun** [comment]
This seems very natural to me. :+1:
