### ISSUE TITLE
Let Ember.debug and Ember Logger return stuff

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/rfcs#140]
### What?

Right now, `Ember.debug` (and its family of logger functions) prints to console then returns nothing, e.g.:

``` javascript
var x = "dog";
Ember.debug(x + 3);
// DEBUG: dog3
// undefined
```

They should be changed so that they return whatever message passed to them, e.g.:

``` javascript
var result, x = "dog";
result = Ember.debug(x + 3);
// DEBUG: dog3
// result == "dog3"
```
### Why?

Suppose we wrote some reasonably intuitive easy-to-understand code, e.g.:

``` javascript
function getRichQuick () {
  return moneyToDrugs( goldToMoney( leadToGold( this.findLead() ) ) );
}
```

During development, it's very likely some or all of the functions used will have errors, and while end users can use console breakpoints, introduce some `function logThru (x) { console.log(x); return x; }`, import such a function from some addon package, or even break the function apart and introduce intermediate variables to `console.log`, it would be far more convenient if `Ember.debug` could just return whatever is passed to it.

Plus this change would be super easy to implement and would be extremely unlikely to break anything.

**Comment by locks** [comment]
As a quick rebuttal, the methods of the aforementioned `console` return undefined.

**Comment by davewasmer** [comment]
> would be extremely unlikely to break anything

I'm not so sure that's the case, especially for `info`, `warn`, `error`:

```js
canDeleteAllTheThings(user) {
  if (!user) {
    return Ember.Logger.error('User was null, this should not happen!');
  }
  return user.get('isAdmin');
}
```

Packages like `ember-cli-rollbar` hook into the logger functions to report errors to third party services, so there are production use cases for calling those functions, like in the code above. In that scenario, returning the message would return a truthy value from that function, leading to significantly broken functionality.

**Comment by mixonic** [comment]
I'm also not wildly in favor of this. The use-case seems fairly un-common. A logged message is not often also used for something else. In fact in the `ember-cli-rollbar` example above, I find it very misleading that the value of `error(` is returned. Is it an object? A string? A boolean?

```js
// An aside, but unsure why this would sometimes return an error
// string, and sometimes a boolean?!
canDeleteAllTheThings(user) {
  if (!user) {
    let msg = 'User was null, this should not happen!';
    Ember.Logger.error(msg);
    return msg;
  }
  return user.get('isAdmin');
}
```

**Comment by foxnewsnetwork** [comment]
I see your point.

Then perhaps not modifying the existing Logger functions but introducing a new `Logger.thru` function or something. I can't speak for the rest of the ember users, but at least I (like Sen. [Ted Stevens](https://en.wikipedia.org/wiki/Series_of_tubes) of the internet in those memes)  tend to think of whatever app I'm building as a series of tubes that pipe into each other. And, if I wanted functionality like my example in the OP:

```javascript
function getRichQuick () {
  return moneyToDrugs( goldToMoney( leadToGold( this.findLead() ) ) );
}
```
And it wasn't working right away I would debug / dev it like so:

1. Throw in my "returns stuff log function" at the first place I suspect might be broken (possibly in the middle if I'm completely unsure):
```javascript
function logThru(x) {
  console.log(x); // or even alert(x)
  return x;
}
function getRichQuick () {
  return moneyToDrugs( goldToMoney( logThru( leadToGold( this.findLead() ) ) ) );
}
``` 
2. Save and run in my browser and see what the console says

3. I find out I misspelled something or mis-ordered some arguments somewhere. I fix it, and now everything works.

4. I delete the `logThru` declaration and the call from the code

I find I often have to do this when I'm writing unit tests, especially when I'm working with big libraries like Ember, lodash, and the like that introduces a ton of "noise" inside the stack trace that makes the error messages rather useless for figuring out what I'm doing wrong and renders the usual break-point-based debugging precarious as one wrong click and I now have to either start over or step through a thousand irrelevant functions (this is especially true when working out deprecation notices that don't throw exceptions (and also, I should mention here in this shamefully nested parenthesis, I am one of poor souls who still use coffee/live-script - the AOL2.0 of js compilers)).

**Comment by locks** [comment]
@foxnewsnetwork this could easily be an addon that comes with wrapper functions, or you could use a functional library like ramda.js: `R.always('thingToReturn')(Ember.Logger.logger)`.

**Comment by sandstrom** [comment]
I think `Ember.debug` is deprecated, so can we close this issue?

**Comment by locks** [comment]
Thanks for the discussion, closing as this should be an RFC if someone wants to further it.
