### ISSUE TITLE
Call set on properties via _super()

### ISSUE THREAD

**Issue by aatkin** [emberjs/rfcs#151]
When creating a new `Ember.Object`, set is called for each property inside a hash passed to `create()`. This works well for regular properties, but may cause unintended behavior when the passed property corresponds to a computed property.

![screen shot 2016-07-07 at 14 48 01](https://cloud.githubusercontent.com/assets/8693728/16680014/a1c57fb6-44f4-11e6-936b-6cc289ba7f7d.png)

I encountered this behavior while debugging our company's Ember application, where a setter of a computed property assumed that the initializer had run. When the object was created with the property, the setter ran before the initializer, causing a error.

A possible solution was proposed in EmberJS community slack channel to call set on properties via `_super()` method, which would allow doing initialization first and then setting the properties.

**Comment by locks** [comment]
Thank you for submitting this issue! I am closing as we are generally moving away from `Ember.Object` and are not looking to make changes to the system.
