### ISSUE TITLE
Let `with` accept and yield multiple arguments

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/rfcs#163]
Is there a reason that `{{#with}}` doesn't accept and yield multiple arguments as the [let addon](https://github.com/thefrontside/ember-let/blob/master/addon/initializers/register-let-helper.js#L7-L9) does? Has this been discussed before? I'd be happy to write up a quick RFC, but I'm wondering if there is any prior art here.

**Comment by nathanhammond** [comment]
`{{#with}}` has been with us since the beginning. Changing its semantics at this point seems likely not in the cards for compat+perf reasons. (Note that I'm not aware of any, but I imagine that both of those problems exist.)

**Comment by locks** [comment]
Plus, the existence of a community addon to fill the void lessens the necessity to do the change internally.

**Comment by rwjblue** [comment]
I'm unsure how that addon will be updated to support glimmer 2. The private API's it hacks into do not exist there...

**Comment by martndemus** [comment]
It can be done with a tagless component.

**Comment by rwjblue** [comment]
@martndemus - Hmmm.  Not really.  There is no way to splat the input arguments.  You could handle the common cases (say 1 to 5 args), but eventually it would fall down.

**Comment by mitchlloyd** [comment]
Based on the feedback it sounds like we shouldn't change `{{#with}}`.

* Speculative compatibility issue
* Speculative performance issue
* Already have community addon that will break in next version of Ember
* Can implement tagless component with positional arguments

I've been convinced that changing `{{with}}` to accept multiple arguments is a bad idea.

So who's going to submit the RFC to remove this feature from Glimmer?

https://github.com/tildeio/glimmer/blob/master/packages/glimmer-runtime/lib/syntax/builtins/with.ts

![screen shot 2016-08-05 at 7 57 53 am](https://cloud.githubusercontent.com/assets/15169/17440372/25887ca2-5ae1-11e6-80e2-98132c2057c8.png)

**Comment by rwjblue** [comment]
I'm not sure it should be removed...

**Comment by mmun** [comment]
As pointed out, this feature is implemented so I'm closing the issue.

On a related note, I hope to see an RFC to pull [ember-let](https://github.com/thefrontside/ember-let) into core sometime soon :). In block form, it's basically a better `with` unless you are relying on `with`'s falsey value behavior. The inline form is unique and reads quite nicely in my experience.
