### ISSUE TITLE
Template should include comparison with other frameworks

### ISSUE THREAD

**Issue by rtm** [emberjs/rfcs#167]
To avoid reinventing the wheel, RFC submitters should be asked to review how other major frameworks deal with the problem being addressed. This should be added to the template.

**Comment by mmun** [comment]
I agree. The [Alternatives section](https://github.com/emberjs/rfcs/blob/master/0000-template.md#alternatives) should be give more helpful direction. E.g. could include the phrases "prior art"and "other frameworks".
