### ISSUE TITLE
Computed property public API

### ISSUE THREAD

**Issue by kellyselden** [emberjs/rfcs#169]
I just want to test the waters on making the computed properties API public. It was delayed in the past [here](https://github.com/emberjs/ember.js/pull/3696#issuecomment-36448879) because of streaming. I'm now using some private API [here](https://github.com/kellyselden/ember-awesome-macros/blob/b2f01fcb2ee02915c526721dd3d78873095a39be/addon/utils.js#L15) and [here](https://github.com/kellyselden/ember-awesome-macros/blob/b2f01fcb2ee02915c526721dd3d78873095a39be/addon/utils.js#L30), specifically `_dependentKeys` and `_getter`. I would love to use public versions of these.

cc @ebryn

**Comment by locks** [comment]
I am closing this issue due to the current shift to tracked properties. Please reopen if this is still relevant!
