### ISSUE TITLE
Shipping a "globals free" build of Ember for the browser

### ISSUE THREAD

**Issue by ebryn** [emberjs/rfcs#172]
Let's explore what it would take for us to be able to ship a build of Ember that doesn't write out the `Ember` & `Em` globals. This would be beneficial for users trying to use Ember modularly within another web application where global pollution is considered a bad practice and in cases where an existing application may be embedding widgets that use different versions of Ember.

We're also using the `EmberENV` global to provide configuration flags from apps. It'd be nice to add another mechanism to configure Ember. Related issue in Ember-CLI: https://github.com/ember-cli/ember-cli/issues/6351

**Comment by cibernox** [comment]
Does it worth to invest on this this with the modules RFC opened and also fulfilling this requirement?

**Comment by locks** [comment]
I believe the global was removed in 3.0.
