### ISSUE TITLE
I'd like to discuss Webpack 

### ISSUE THREAD

**Issue by martndemus** [emberjs/rfcs#177]
With all the new modularization happening I'd like to champion swapping Broccoli out for Webpack in Ember CLI.

Without writing a big wall of text, here's my short outline of why:
- Broccoli is (pretty much) exclusive to Ember.
- Vue, Angular, React and a good few independant projects use Webpack, I've tried some of these in the past week and it's suprisingly easy to add dependencies.
- Webpack will give Ember CLI better support for generic packages. I think this will become the key pain point of keeping Broccoli around.
- Webpack has better documentation on writing plugins for webpack, this is pretty much undocumented in Broccoli's case.
- I'm sure we can make it work for existing pure ember (non-'cli') addons, without breaking much. I guess we'll need a transition period for the addons  that do, although some will become obsolete too.

TL;DR I think it is time to admit Broccoli is a dead end street and that Webpack will bring more benefits to Ember.

**Comment by rwjblue** [comment]
IMO, this is likely better suited for ember-cli/rfcs.

(and I disagree with you 😉, but we can chat over there about it)

**Comment by martndemus** [comment]
Ugh, why does Ember CLI have it's own RFC repo?

**Comment by mkay581** [comment]
did you really expect for it to be that easy? 😉 I actually like the proposal but I'll save my comments for that PR

**Comment by nathanhammond** [comment]
Note that we have had _numerous_ conversations on this topic. I also disagree with the proposal. Regardless, this issue should be locked and closed, we'll discuss at `ember-cli/rfcs`.

**Comment by rwjblue** [comment]
Moved to https://github.com/ember-cli/rfcs/issues/79, closing here...

**Comment by stefanpenner** [comment]
> Webpack has better documentation on writing plugins for webpack, this is pretty much undocumented in Broccoli's case.
> I'm sure we can make it work for existing pure ember (non-'cli') addons, without breaking much. I guess we'll need a transition period for the addons that do, although some will become obsolete too.

is orthogonal to broccoli vs webpack.
