### ISSUE TITLE
Promise-aware Ember.get and Ember.set for paths

### ISSUE THREAD

**Issue by buschtoens** [emberjs/rfcs#183]
Okay, so the bigger plan is that promises should become a first class citizen in Ember.js and using `async / await` functions should feel natural. Async stuff should "just work" :tm: .

In our app we adopted async functions and for the most part it feels great.

But there's one main pain point: `Ember.get` and `Ember.set` don't properly work with promises.

They *kinda* do for Ember Data relationships, because these aren't just regular promises, but magic `DS.PromiseProxy`s. They still suck when these relationships aren't yet resolved.

### Problem demonstration / contrived example

```js
// app/models/post.js

export default Model.extend({
  title: attr('string'),
  body: attr('string'),
  author: belongsTo('user')
});
```
```js
// app/models/user.js

export default Model.extend({
  username: attr('string'),
  posts: hasMany('post')
});
```

```js
// app/post/route.js

export default Route.extend({
  model({ post_id: id }) {
    return this.store.find('post', id);
  },

  async afterModel(post) {
    this.set('username', await post.get('author.username')); // this line is important
  },

  setupController(controller, post) {
    controller.setProperties({ post, username: this.get('username') });
  }
});
```

In this example (for whatever reason) I want to set the `username` property on the controller. Assume that the API does not include the `author` in the original response.

Look at the `afterModel` hook.

Now accessing `post.get('author')` returns a `DS.PromiseObject` that resolves after the related `user` record has been retrieved from the server. Directly accessing `post.get('author.username')` does not work and synchronously returns `undefined`.

So as it turns out, the example above doesn't work. We have to make some adjustments:

```js
async afterModel(post) {
  this.set('username', (await post.get('author')).get('username'));
}
```

Thanks to async functions this doesn't look as bad as it could.

```js
afterModel(post) {
  return post.get('author').then(author => {
    this.set('username', author.get('username');
  });
}
```

Using `async / await` it's still not as good as the original example. But it could be.

#### Ember.get

Currently, when passing a path to `Ember.get`, this path is traversed as far as synchronously possible. This means that `Ember.get` already supports promises, when using the `PromiseProxyMixin`, but only when they are already fulfilled.

If `Ember.get` encounters a promise that is still unfulfilled, it bails out by returning `undefined`.

Instead, `Ember.get` should then wait for this promise to resolve and continue traversing the path. This waiting behavior is recursive.

This means that you could even do advanced stuff like `post.author.friends.firstObject.username`.

If any of the promises down the line reject, the promise returned by `Ember.get` rejects with that error / reason.

A point I'd like to discuss: What if, down the line, a synchronously accessible property is `undefined` or a promise resolves to `undefined`. Do we still resolve the promise with `undefined` or do we reject it with a descriptive error? This is new terrain.

As a concrete example: What if `post.author.friends` resolves to an empty array? [`firstObject`](http://emberjs.com/api/classes/Ember.Enumerable.html#property_firstObject) would be `undefined` and subsequently, by the current semantics (if all promises would have been resolved before trying to get the value) `Ember.get` would return `undefined`, as it cannot proceed traversing to `username`.

Should we do the same? Or should we reject with a more descriptive error since we're in already in promise-land anyways?

#### Ember.set

Currently behaves pretty much the same way as `Ember.get`. When given a path that only has fulfilled promises (or to be more precise, objects with the `PromisProxyMixin`), `Ember.set` traverses that path and sets the value accordingly.

If it encounters an unresolved proxy, we get this error:

```
Assertion Failed: Cannot delegate set('foo', bar) to the 'content' property of object proxy <(subclass of Ember.ObjectProxy):ember1179>: its 'content' is undefined.
```

Which makes sense, since the `PromiseProxyMixin` takes care of setting the `content` property after the promise is resolved.

When we just pass in a good ol' regular `Ember.RSVP.Promise`, `Ember.set` just **blindly sets the value on the `Promise` object.**

This makes me sad.

I'd want `Ember.set` to wait for promises to resolve and traverse them down. If a promise rejects or resolves to an undefined value down the line, we'd reject the promise returned by `Ember.set`.

---

What do you folks think? Is this worth writing up as a RFC? Should the scope be broadened?

I'll see, if I can find the time to write an addon that basically gives you promise-aware `Ember.get` and `Ember.set`.

**Comment by buschtoens** [comment]
A potential problem I see with the proposed `Ember.set` semantics:

Currently, when promises down the line were not fulfilled, `Ember.set` throws. The following code is not executed. With the new semantics, `Ember.set` would just wait in the background and return a promise, that could potentially reject, when the actual promise we're waiting for resolves as `undefined` or rejects.

Using async functions, this is no problem at all and intended behavior:

```js
(async () => {
  try {
    await Ember.set(resolvesToUndefined, 'foo', 'bar');
  } catch (err) {
    console.log('gotcha');
  }
})();

// vs

(() => {
  try {
    Ember.set(resolvesToUndefined, 'foo', 'bar');
  } catch (err) {
    console.log('gotcha'); // never called!
  }
})();
```

On the one hand you could argue that this is a backwards incompatible API change, as setting values on unfulfilled `PromiseObject`s doesn't synchronously throw anymore. On the other hand, you could argue that this wasn't really the expected behavior in the first place.

I'd be okay with hiding the new semantics behind a feature switch. But they'd have to be baked right into `ember-metal` to be able to take full advantage of them. Monkey-patching `Ember.get` and `Ember.set` via an addon probably won't work to well for stuff like `this.get`.

**Comment by mehulkar** [comment]
@buschtoens is this still relevant after Octane? I think ember is generally moving away from get/set right?

**Comment by buschtoens** [comment]
Thanks for cleaning up my dead corpses! Haha. 😄 

Yes, this is definitely obsolete. 👴
