### ISSUE TITLE
Support computed properties that are re-calculated only on value change AKA changeGate, computedGate, computed shortcut

### ISSUE THREAD

**Issue by givanse** [emberjs/rfcs#189]
Computed properties are marked as dirty on object change, even if the actual value has not changed.

ember twiddle test case:

[<img width="517" alt="screen shot 2016-12-10 at 9 42 42 pm" src="https://cloud.githubusercontent.com/assets/431270/21078378/a30adb12-bf21-11e6-9afd-f333e8de9db1.png">](https://ember-twiddle.com/aba70cf706232a8e48c230a9ab46494f?fileTreeShown=false&openFiles=controllers.application.js%2C)

That twiddle uses the solution provided by the ember addon [ember-computed-change-gate](https://github.com/GavinJoyce/ember-computed-change-gate).

There is also this example that illustrates the benefits of this feature:
[computed short (computedGate)](https://twitter.com/Runspired/status/807048801995276289)

[![computed short](https://cloud.githubusercontent.com/assets/431270/21078360/0c4f06f8-bf21-11e6-8b93-a0bc242da6c5.png)](http://imgur.com/a/fRtqN)

So, the idea that comes to mind is to have something like this:

```
Ember.Object.extend({

  foo: Ember.computed.value(function() {
    // notifies that the property `foo` changed only if
    // the final result has a different value
  }),

});
```

`Ember.computed.value` felt like the right syntax, since we already have similar computed methods ([`Ember.computed.alias`](http://emberjs.com/api/classes/Ember.computed.html) etc.)

**Comment by givanse** [comment]
On further thought, if we had this, would anybody still use `Ember.computed`. Seems like not, therefore this would then need to be the default behavior?

**Comment by stefanpenner** [comment]
We have talked about doing this being default for CP's, for quite some time. I believe the issue that blocked this from being the default is that the contract for `willChange` and `didChange` events is that they are always paired.

@krisselden likely has better memory of this.

That being said, the gain was never demonstrated maybe this is sufficient evidence to thoroughly investigate.

**Comment by jonnii** [comment]
@stefanpenner my understanding of glimmer 2 is that the value change tracking there in effect achieves the same thing at the DOM level, is that correct?

**Comment by stefanpenner** [comment]
@jonnii ya, the above would be pushing this throughout the stack (which many believe is worth exploring)

**Comment by givanse** [comment]
I have lost track of what Glimmer 2 is doing these days. Has it done anything that may render this idea obsolete?

**Comment by Gaurav0** [comment]
No, computed properties recalculate the same way. Also, `@tracked` invalidates when you set the value, even without calling `set` explicitly, when you change it, even if you change it to the same value.

That's why `this.value = this.value;` is the new `this.notifyPropertyChange(this, 'value');`

**Comment by pzuraq** [comment]
Unfortunately with autotracking this wouldn't really be possible anymore. Since all changes are pull based, we must rerun the codepath to even see if something may have changed. Otherwise, we wouldn't even have an opportunity to compare the previous value with the current one.

**Comment by givanse** [comment]
Ok, so it is leaning fully on the idea of letting the JS churn, it is fast; and, the rendering engine will skip updates as necessary?

**Comment by rwjblue** [comment]
Yes, that is the idea. It will also avoid invoking the things like getters if we are certain no tracked state was consumed (or has been dirtied/invalidated).
