### ISSUE TITLE
Lookups in non-injected objects

### ISSUE THREAD

**Issue by ctusch** [emberjs/rfcs#198]
_I've erroneously posted this on the main repository and have been redirected here._

I've repeatedly stumbled across the following problem:

If you create an object using `create` (instead of `ApplicationInstance.lookup`) you can't use `Ember.inject` inside of it. Also you can't use `Ember.getOwner(this)` within that object in order to use `lookup`.

I understand the technical reason why this is so and I also understand that I can set the owner of the object. But I don't think this is a satisfying "workaround".

My use case is as follows. I have a dashboard which can contain several widgets. The dashboard configuration (along with the widgets' class name) is stored in a database. Now the widget library can be extended by 3rd party developers by writing an Ember add-on. This is not important to the topic but the main point is those are mostly inexperienced developers.

The widgets can hold custom objects. The classes are extending `Ember.Object`. For those custom objects to use services they need to have an owner. Of course when creating such an object myself I will think of passing an owner most of the time. But I can't expect inexperienced developers to do so. If they forget or don't know about it the resulting error message won't help them much.

Another possibility would be to `register` all custom classes with the `Application` and then use `lookup` to create the instance. But 3rd party developers could also add custom classes and this is an advanced concept to explain.

I don't feel that creating custom classes is an "advanced technique" and should come with such limitations. The solutions seem very daring to a beginner. It puts the burden on the developer.

Sadly I can't really come up with a better solution so I guess this issue will get closed soon. If I'm not mistaken assigning a default owner wouldn't work because with engines you wouldn't know which instance is the right one.

But my hope is that some of you Ember developers might understand how unsatisfying the current situation is and maybe you can think of something that might be better.

Thank you for reading!

**Comment by webark** [comment]
@ctusch would they be able to, rather then extending a plain `Ember.Object` extend a custom "Widget" class that they could import which would be pre registered?

**Comment by webark** [comment]
But maybe some type of "other" object that is registerd to the application wouldn't nessicarily be a bad idea in general.

**Comment by nathanhammond** [comment]
You can probably set up the base widget class that you're extending to do the handling you need inside of `init`. Coding in GitHub, just a sketch for you to start from–it's possible that this doesn't work at all.

```javascript
const Widget = Ember.Object.extend({
  init() {
    // Some fancy code to set up the owner.
  }
});

// This would be the interface for less-experienced devs and yet it "just works."
const ChartWidget = Widget.extend({
  /* ChartWidget methods here. */
});

let chartWidgetInstance = ChartWidget.create({ /* ... */});
```

**Comment by ctusch** [comment]
@webark Thank you for your input! For the widget I already have a base class they have to extend (which extends from `Ember.Component`). The problem in my specific case is with the custom objects that  a widget holds in its properties.

So I tried out your idea like this (please tell me if I got you wrong):
```JavaScript
    const applicationInstance = Ember.getOwner(this);
    const BaseClass = Ember.Object.extend();
    applicationInstance.register('custom:base-class', BaseClass, { instantiate: false});
    const InjectedBaseClass = applicationInstance.lookup('custom:base-class'); 

    // using BaseClass instead of InjectedBaseClass won't work
    const MyClass = InjectedBaseClass.extend({ myService: Ember.inject.service() });
    const myClass = MyClass.create();

    // this works!
    const value = myClass.get('myService.value');
```
It really surprised me that it actually worked. I did some research and the reason seems to be in `/packages/container/lib/container.js`'s `injectDeprecatedContainer` function. Unfortunately this is going to be removed with Ember 3.0.0.

The other problem why I can't even use it at the moment is that `MyClass` would most likely be defined within its own module where it would be impossible again to access the `ApplicationInstance` and hence `lookup` (it is a variation of the original problem).

**Comment by ctusch** [comment]
@nathanhammond Sorry, I didn't see your post earlier! I think some clarifications can be found in my previous answer to webark.

But this is more or less my problem. What code could I put in `init`? There is no official way (that I know of) I can get the `ApplicationInstance`. And passing it to `create` every time is what I wanted to avoid.

**Comment by webark** [comment]
@ctusch hmm.. I thought you could get access to the main container, or that you could add your own injections.. but I guess you can't anymore that I'm aware of.. maybe you never could.. sorry. The best solution that I could see immediately was to just create a computed property that they would have to import. This is a sample utility.

```javascript
// utils/make-owned-object
import Ember from 'ember';

const {
  computed,
  getOwner,
} = Ember;

export default function makeOwnedObject(Item, properties) {
  return computed({
    get() {
      return Item.create(Ember.assign(properties, { container: getOwner(this) }));
    }
  });
}
```
```javascript
// models/plain-object
import Ember from 'ember';

const {
  Object,
  inject: { service: injectService },
} = Ember;

export default Object.extend({
  inPlainObject: injectService('in-object'),

  other: 'cool',
});
```
that you could then have them use like.
```javascript
import Ember from 'ember';
import makeContainedObject from '../utils/make-owned-object';
import PlainObject from '../models/plain-object';

const {
  Component,
} = Ember;

export default Component.extend({
  plainObject: makeContainedObject(PlainObject, {
    peace: 'here',
  }),
});
```
Maybe someone will have a better solution that out there. Sorry for giving you slightly higher hopes before.

**Comment by ctusch** [comment]
That's a pretty cool idea! Sadly, while it makes things a bit easier, you still have to remember to use it every time.

I'm really thinking about stop using Ember service and instead using normal singletons. That way I can just import them wherever I need them. It kind of defeats the purpose of services if you can't use them as you normally would as soon as you start to make your own Ember objects.

**Comment by locks** [comment]
@ctusch the purpose of services is that the framework manages their lifetime, if you don't need that, then you don't need services :P

**Comment by ctusch** [comment]
@locks I'm not sure but is there anything going on besides lazy loading?

My thinking is that if Ember advertises services as

> an Ember object that lives for the duration of the application, and can be made available in different parts of your application.

then this should hold true for all parts of an application that are "made" with Ember. What good is a logging service if I can't access it?

I know that it isn't really the service that's the problem but rather that there is no lookup mechanism available inside of normal Ember objects. But missing service injections is what hurts most.

**Comment by workmanw** [comment]
FYI, I think if you're manually creating objects you should use the [ownerInject](http://emberjs.com/api/classes/Ember.ApplicationInstance.html#method_ownerInjection), rather than trying to manually inject the `container` instance. We do this a little bit in our app with great success (though we try to limit it to only a few cases where it's absolutely necessary). 

One use case we have is our ajax service throws custom errors from a variety of ES6 classes. In some cases those error classes need to use `service:i18n` to build the property human readable error string.

**Comment by webark** [comment]
@workmanw didn't know about that API! Thanks for sharing. :)

**Comment by locks** [comment]
> I know that it isn't really the service that's the problem but rather that there is no lookup mechanism available inside of normal Ember objects. But missing service injections is what hurts most.

That's what I mean, the special sauce isn't because it's an `Ember.Object`, it's because the application instantiates it and injects itself (the owner). You can't really have dependency injection if you don't have a container to get the dependencies from in order to inject.

**Comment by ctusch** [comment]
@workmanw Thanks for the hint! That's at least an official API so this seems to be the way the Ember team envisioned it.

@locks Maybe a solution would be to, as @webark suggested, implicitly register all classes in a certain directory. I don't know how this works for `components` etc. but I guess Ember CLI parses all modules in that directory and adds calls to register them.

So there could also be a `classes` directory or something similar where one would put such other `Ember.Object`s. Those could then be looked up via the `ApplicationInstance` and therefore would be able to have other dependencies injected.

This could be one way to keep a consistent developer experience. What do you think?

**Comment by locks** [comment]
@ctusch everything under `/app` is reachable by the resolver. By default, things looked up from the container are singletons, but you can customize the registry so it returns non-singletons. Here's a simple lookup: https://ember-twiddle.com/879b741d13963389fbd6143abd552614?numColumns=2&openFiles=routes.application.js%2Croutes.application.js

**Comment by webark** [comment]
@locks didn't know the resolver "gobbled" up everything as it went along. Thanks for sharing! Is that going to be the same when we transition to the new "module unification" resolver?

**Comment by locks** [comment]
@webark the unification resolver will have some new semantics, like private namespaces, so I'm unsure about the changes at this moment!

**Comment by ctusch** [comment]
@locks Thanks, this is almost perfect!! This is what I've been looking for. I wasn't aware that all the modules could be loaded through the registry.

For those wondering why locks used `some-object:classes` as the lookup name in his example instead of `classes:some-object`: This way the `podBasedModuleName` lookup pattern gets a match.

The problem with the `defaultModuleName` lookup pattern is that it pluralizes the type. It does so by simply appending an `s` at the end of the type. So `class:some-object` would become `classs:some-object`. My workaround is to use an `objects` directory instead of `classes`. This way you can use `object:some-object` to lookup an instance of `some-object`. One could even customize this by extending the [`DefaultResolver`](http://emberjs.com/api/classes/Ember.DefaultResolver.html).

The other point locks mentioned, returning new instances instead of a singleton by default, can also only be implemented with the `defaultModuleName` "syntax". In the case where you use `object` to lookup your instances you can simple use `application.registerOptionsForType('object', { singleton: false })`.

[Here is a twiddle that brings this all together.](https://ember-twiddle.com/ea20786c96e6817b39d0335e321a81b8?openFiles=templates.application.hbs%2C)

I think this is a concept that is teachable. One caveat is that you can't create instances of such objects directly in the object literal of e.g. a component. You have to wrap it in `Ember.computed` or put it in your  `init`. But this is advisable anyway since otherwise that object instance would be shared across all your component instances.

I'm going to  close this issue. Thank you all for your support and sorry for littering the RFC repository with this.

**Comment by webark** [comment]
@ctusch didn't know about the `registerOptionsForType`.. thats a nice api too! Just thinking about getting take away from this to better the community as a whole, but would you say that there could be another section under the "Application Concerns" that goes into this a little better? Or maybe after rereading that section stuff makes more sense, and we could tweek it a little bit?

Was just seeing if there was a way we could take your 

> Thanks, this is almost perfect!! This is what I've been looking for. I wasn't aware that all the modules could be loaded through the registry.

moment and spread that ❤️ 💡

**Comment by ctusch** [comment]
@webark Hm, hard to say. I would say most of the information is there. What could be added is that it's possible to manually create a container-owned object with `applicationInstance.ownerInjection`.

And maybe the possibility to lookup nearly any module (and thus make it a container-owned object) without the need to register it. Though I feel that this might be a bit too hacky to include it in the guide because you can "only" go one directory deep and the issue with pluralization.

Maybe the use of `Object.create` by beginners should be discouraged in general. Or maybe there should be a warning in the parts of the guide that mention it that one loses all those benefits by using it.
