### ISSUE TITLE
Status of active RFCs

### ISSUE THREAD

**Issue by courajs** [emberjs/rfcs#206]
Often I have questions about the status of an RFC I remember was merged a little while ago: Has there been work done to implement it? Any tasks I can pick up and help with? Who's the champion for it? Or even, which Ember version was it released in?

I think it would be nice if each active/merged RFC had a home somewhere I could go to look at these things. Does something like that exist? If not, are others interested in having these? Would it be more or less work for maintainers?

**Comment by rwjblue** [comment]
I believe that the learning team has been working on a feature dashboard for exactly this purpose. 

Maybe @locks / @acorncom can chime in on that?

**Comment by locks** [comment]
I have reached out to @courajs on Slack, we'll be working on https://github.com/emberjs/website/pull/2726. Closing this issue so we can track changes there.
Thanks for helping out!
