### ISSUE TITLE
`Ember.compare` respecting objects that implements `valueOf`

### ISSUE THREAD

**Issue by ming-codes** [emberjs/rfcs#207]
Cross linking from emberjs/ember.js#14892

> JavaScript convention to compare objects is to allow the object to implement the `valueOf` method to convert it into a primitive so it can be compared. It does not looks like `Ember.compare` respect this.
>
>```js
>Ember.compare({ valueOf() { return 1; } }, { valueOf() { return 2; } }); // actual 0; expected -1
>```

`Ember.compare` is being used internally by `Ember.computed.sort`.

**Comment by rwjblue** [comment]
I believe that we should probably fix `Ember.computed.sort` to use `valueOf` and deprecate `Ember.compare` / `Ember.Comparable` in favor of just "using the platform" (e.g. the deprecation would suggest you switch to use `.valueOf` instead).

Would love help from someone willing to work on an RFC for that...

**Comment by pixelhandler** [comment]
@rwjblue so a full RFC is needed vs issue here?

**Comment by rwjblue** [comment]
Yeah, we need an RFC for deprecations of public API.

**Comment by pixelhandler** [comment]
@ming-codes are you up for writing an RFC PR? seems necessary

> Yeah, we need an RFC for deprecations of public API.

**Comment by locks** [comment]
Closing due to no longer being relevant.
