### ISSUE TITLE
Move `concatenatedProperties` and `mergedProperties` to class level

### ISSUE THREAD

**Issue by Serabe** [emberjs/rfcs#209]
Currently, these properties are set at an instance level even if changes on them are not taken into account (see [example](https://ember-twiddle.com/2a1f4675eaa0245d00d00ed1841304b6?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs)).

I suggest moving these to class level:

```js
// Now
Ember.Component.extend({
  concatenatedProperties: ['arr'],
  mergedProperties: ['hash']
}).reopenClass({
  positionalParams: ['hello'],
});

// Suggested
Ember.Component.extend().reopenClass({
  concatenatedProperties: ['arr'],
  mergedProperties: ['hash'],
  positionalParams: ['hello']
});
```

Current implementation is at mixin level, so there is no notion of class, just a bunch of objects, so the implementation would change a lot and there will be a time that both need to be supported which, honestly, can be a bit of a pain.

Nevertheless, solving bugs like emberjs/ember.js#14914 would be easier to fix (and in a more performant way).

The only downside I can think of is for those adding `concatenatedProperties` or `mergedProperties` in a mixin (and those using those mixins). Then, two different mixins need to be provided.

**Comment by cibernox** [comment]
Forcing people to use `.reopenClass` is sad because of usability, but with ES6 classes and decorators it could be much nicer (thinking ahead of present, I know)

```js
@concatenatedProperty
classNames: ['foo', 'bar']
```

**Comment by locks** [comment]
With glimmer components having shipped, this is unlikely to change and the ergonomics are now much better (I hope at least!) Thank you for the discussion :)
