### ISSUE TITLE
Experimenting with Mobx

### ISSUE THREAD

**Issue by mdebbar** [emberjs/rfcs#210]
In general, I believe it's a good idea for OSS projects to benefit from each other whenever possible. [Mobx](https://github.com/mobxjs/mobx) is a library specialized in handling dependency graphs and computed properties. That means the implementation is likely more efficient than ones in a general-purpose frameworks such as Ember.

Mobx seems to have a few advantages that Ember can benefit from:
- Mobx observers don't have the caveats that Ember observers have.
- Mobx automatically maintains a graph of property dependencies that's very efficient and scalable.
- Devs don't need to specify dependent keys for computed properties, Mobx handles that automatically. This is a big source of problems from my experience with Ember.
- Ember doesn't have to maintain a lot of code that handles observers, computed, etc.

I'm curious if anyone has experimented with incorporating mobx into Ember Objects to track observers and computed properties. If not, would that be something of interest to the Ember team?

**Comment by mdebbar** [comment]
This is intended as an idea to experiment with integrating mobx inside ember. I mainly want to answer a few questions before I attempt writing an RFC:
1. Has anyone thought about this before.
2. Is it worth doing such an experiment.
3. Are there any objections to doing an integration like this.

**Comment by stefanpenner** [comment]
cross posted comment: https://github.com/emberjs/ember.js/issues/14973#issuecomment-283396971

**Comment by auvipy** [comment]
https://discuss.emberjs.com/t/porting-mobx-ideas-to-ember-js-dependency-less-properties/10796/7

**Comment by rwjblue** [comment]
I believe this is directly addressed by the tracked properties work (whcih is "close" to being enabled by default). Closing for now...
