### ISSUE TITLE
isEqual missing

### ISSUE THREAD

**Issue by daniel-de-wit** [emberjs/rfcs#222]
I've noticed Ember.isEqual is never mentioned in the RFC?

https://emberjs.com/api/#method_isEqual

**Comment by Serabe** [comment]
`Ember.isEqual` has been in Ember much longer than the RFC process.

**Comment by pixelhandler** [comment]
@rwjblue can you close this one, the method pre-dates the RFC process.

@daniel-de-wit which is "the RFC" do you have a PR or other RFC issue in mind? If so you can comment directly on that issue/pr instead.

**Comment by daniel-de-wit** [comment]
@pixelhandler @Serabe 
Excuse me, for some reason I thought every RFC was it's own repo. Was not paying attention..

The RFC I was referring to is https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md.

I've been using the 'ember-new-modules-shim' for a while now and noticed the `isEqual` was missing in the shim and reported it there, they in turn said it was not in the 0167 Javascript Module API RFC so I should first confirm it here. See https://github.com/DockYard/ember-new-modules-shim/pull/3
