### ISSUE TITLE
Add `titleize` to Ember.String

### ISSUE THREAD

**Issue by kellyselden** [emberjs/rfcs#224]
Seems like a missing piece. It is "polyfilled" by https://github.com/romulomachado/ember-cli-string-helpers#titleize.

Only downside is expanding Ember.String API.

cc @romulomachado

**Comment by kellyselden** [comment]
Also cc @martndemus

**Comment by locks** [comment]
I'm very wary about expanding Ember API, and doubly so for prototype extension APIs.
Is this not provided by `lodash` or a similar utility belt?

**Comment by stefanpenner** [comment]
LIkely the big question will be why part of core and not an addon?

**Comment by romulomachado** [comment]
It's worth mentioning that the addon only provides a set of template helpers and does not to polyfill Ember.String.

**Comment by kellyselden** [comment]
It could definitely live in an addon. I just ran into an instance where I figured it was already there and was surprised when it wasn't. That's motivation for me to open an RFC for discussion.

**Comment by SpikedKira** [comment]
Seems like a slippery slope. Perhaps the answer is to only include the ones that Ember itself has need for.

**Comment by aureliosaraiva** [comment]
If not used by the core, I believe the best would be add with addons.

**Comment by locks** [comment]
Closing this as we have extracted `@ember/string` to its own package. If this feature is still desired, please open an issue on https://github.com/emberjs/ember-string 😁
