### ISSUE TITLE
Restore unique history location state

### ISSUE THREAD

**Issue by courajs** [emberjs/rfcs#227]
RFC #186 introduced per-history-entry unique ids to the HistoryLocation.

But currently on app boot, a new uuid is always generated. This means that when refreshing the page, the same history entry is given a new uuid.

Instead I think we should check `history.state` for existing state information, and use that if it's available. This would allow an addon to restore things such as scroll position, in line with the motivation of the original RFC.

I believe this would be a fairly straightforward change [here](https://github.com/emberjs/ember.js/blob/1e5b8a90f82d1e81cb673c4f1f6e3a8fdd5a6a2c/packages/ember-routing/lib/location/history_location.js#L67), which I'd be happy to work on if no one sees any issues.

**Comment by stefanpenner** [comment]
this may be considered a bugfix and not require an RFC?

**Comment by courajs** [comment]
I just brought it up here since it wasn't specified in the original RFC. I'm happy to move it!

**Comment by courajs** [comment]
Bugfix PR opened: https://github.com/emberjs/ember.js/pull/15223
