### ISSUE TITLE
Make it possible to differentiate between helpers and properties

### ISSUE THREAD

**Issue by initram** [emberjs/rfcs#245]
In template code to write out a property named "icon" you would do like this {{icon}}, this is fine. The problem is when someone comes along and defines a helper (either locally or in a dependent extension) called "icon" as well, then the code suddenly means something different (it will use the icon helper instead of the icon property).

So I suggest that you add a way of specifying whether you reference a property or helper, or disallow helpers with no arguments. 

Another possibility would be to put extensions into "namespaces", as you are not in control of when extensions add new helpers that may name clash with your properties. Having all helpers from all extensions in "global scope" is just a name clash waiting to happen.

**Comment by Panman8201** [comment]
Don't quote me on this, but I think if you do `{{this.icon}}` you will get the property for sure.

**Comment by mmun** [comment]
@Panman8201 is right. It's something we might consider enforcing in Glimmer templates.

**Comment by locks** [comment]
This has been addressed via requiring a prefix, whether `this` or `@` for named arguments!
