### ISSUE TITLE
Ember.computed.includes

### ISSUE THREAD

**Issue by sandstrom** [emberjs/rfcs#247]
The most common long-form computed property in our project are simple checks to see if some array contains a string.

Would you be open to adding this functionality as a computed property?

```js
// wasteful
hasBanana: function() {
  return this.get('possessions').includes('banana');
}.property('possessions', 'banana'),

// wonderful
hasBanana: Ember.computed.includes('possessions', 'banana'),


// usage
let hamster = Hamster.create();

hamster.get('hasBanana'); // false

hamster.set('possessions', ['orange']);
hamster.get('hasBanana'); // false

hamster.set('possessions', ['banana']);
hamster.get('hasBanana'); // true
```

***

*No RFC yet, just want to get initial reactions.*

**Comment by NLincoln** [comment]
This would work great in an addon like `ember-awesome-macros`

**Comment by NLincoln** [comment]
https://github.com/emberjs/ember.js/pull/13831 

Also this was brought up over a year ago, and wasn't accepted.

**Comment by sandstrom** [comment]
@NLincoln Yeah I know, I don't understand why though 😄

**Comment by workmanw** [comment]
I added an RFC for `computed.sortBy` and it had a more lengthy discussion about adding new computed properties in general. That might be relevant to providing some back story: https://github.com/emberjs/rfcs/pull/87

**Comment by sandstrom** [comment]
@workmanw Thanks, much appreciated! 😄 

Got it, I'll just assume the moratorium stands and close this. While I don't agree it's not a biggie and the addon-route is a simple one.

**Comment by workmanw** [comment]
@sandstrom 👍  -- FWIW I too feel like everything on `Ember.Enumerable` should be a first party computed macro. Using an addon is easy, but not always initiative for new users.

**Comment by webark** [comment]
@sandstrom one thing that I know has been tossed around before is moving the majority of the computed properties into an addon and then having that addon be included in ember-cli in the default blueprint. I think an RFC around that could potentially get more traction and by in.

**Comment by webark** [comment]
this would give the "novice" user more default "tools", but allow the core to be smaller and allow people who are more familiar with the eco system the control they might desire.

**Comment by locks** [comment]
@sandstrom @NLincoln I just want to point out that the PR was not accepted due to the lack of the respective RFC.

**Comment by sandstrom** [comment]
@webark Good point! Though one downside with including things in ember-cli that adds API-surface, is that it won't be covered in the guides or documentation. It may be that useful to newcomers.

What would be some computed property macros that people think should be included? What is a reasonable upper limit or cap, where should one draw the line (if the set is to be included in ember-cli by default)?

Suggested CPMs:
- `sortBy`
- `includes`

Here is some inspiration:
https://www.npmjs.com/package/ember-awesome-macros
https://www.npmjs.com/package/ember-cpm
https://www.npmjs.com/package/ember-computed-sortby

**Comment by locks** [comment]
> Though one downside with including things in ember-cli that adds API-surface, is that it won't be covered in the guides or documentation.

Are you saying that Ember Data isn't covered in the guides or documentation? ;)

**Comment by sandstrom** [comment]
@locks Good point 😄  Maybe it could be added to the docs, I don't know enough about the documentation part of Ember to answer

**Comment by locks** [comment]
Is this still relevant in the current tracked properties world?

**Comment by sandstrom** [comment]
@locks Probably not, I'll close this for now. Can reopen later if closing was a mistake.
