### ISSUE TITLE
Missing ObjectProxy and PromiseProxyMixin in javascript-module-api

### ISSUE THREAD

**Issue by rmmmp** [emberjs/rfcs#248]
It's missing in the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) yet I see `ArrayProxy`. Is this intentional?

**Comment by rwjblue** [comment]
I haven't dug into this specific set of things yet, but wanted to point you to https://github.com/ember-cli/ember-rfc176-data which is where we are tracking the mappings in a go forward manner. The original RFC is unlikely to get updated now that it is merged.

Closing this issue, but feel free to reopen over in https://github.com/ember-cli/ember-rfc176-data.
