### ISSUE TITLE
Make Ember Array.prototype extensions non-enumerable

### ISSUE THREAD

**Issue by Cobertos** [emberjs/rfcs#251]
Ember's extension of `Array` adds properties which are enumerable. These properties are necessary for Ember's functioning but their enumerability causes issues when trying to use them with `for...in` loops or anything else that heeds the enumerable flag. This is a proposal to make the properties non-enumerable.

The reasoning behind this proposal is that ES6 uses non-enumerable properties with the Array built in object. So you won't see things like `.fill` or `.forEach` when iterating over an array with `for...in`. The specification states that [in creation of a method property, the enumerable property is false](https://www.ecma-international.org/ecma-262/6.0/#sec-createmethodproperty). I'm pretty sure that the Array prototype object uses `enumberable = false` for its method definitions and I'm definitely sure that [user defined class evaluations use `enumerable = false` for its method definitions (see Step 21)](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation). Testing within the Chrome shows this to be true at least for that environment:

![image](https://user-images.githubusercontent.com/6759176/30292987-12078738-9706-11e7-89a7-e3bf74c17ddc.png)

[This twiddle](https://ember-twiddle.com/b050e5017f642d1f31388adb2fbb29d7?openFiles=controllers.application.js%2C) demonstrates the current functioning of Ember with respect to for...in loops. The expected output would be to show nothing.

Currently I'm using a workaround that involves an application initializer that iterates over the Array prototype and sets all the enumerable properties to unenumerable.

```
/**
Edits Array.prototype enumerable properties
*/
export function initialize() {
    for(let prop in Array.prototype) {
        let origPropDesc = Object.getOwnPropertyDescriptor(Array.prototype, prop);
        Object.defineProperty(Array.prototype, prop, Object.assign(origPropDesc, {enumerable:false}));
    }
}

export default {
    name: "array-enumerability-edit",
    initialize,
};
```

**Comment by locks** [comment]
Closing as no longer relevant as the project's moving towards tracked properties.
