### ISSUE TITLE
ember issues since 2012. Maybe is there a way today? Integrating Push to Keep Client Data in Sync, Local Storage Support, Handling Bad Connections and Crashes: Gateway to Offline Support

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/rfcs#254]
I found this post from 2012 http://hawkins.io/2012/07/ember_wish_list/.

Since then something is changed, but not these points:

- **Low Hanging Fruit - Integrating Push to Keep Client Data in Sync**
All complex applications allow data manipulation outside of user interaction. I mean not all data changes are done by users sitting on there devices. The server may be syncing something in the background which brings in new data. How is the client going to know about it? Is it periodically polling the server? That's crazy. It's easy to write code that pushes all changes. It should be equally easy to push that data into data store regardless of what push service you're using. Ember-data stores should define a simple interface to accept messages over push. Perhaps, the store itself is a web socket client which can be connected to your push stream. There are many different ways to do this. Everyone will solve this uncomplicated problem in the same way. This is exactly why the framework should do it. Ideally, there should be no problems if you switch from Websockets/Pusher/Faye/PubNub/Boxcar/etc. The messages always arrive.
Issue for this single point here: https://github.com/emberjs/rfcs/issues/255

- **Low Hanging Fruit - Local Storage Support in Ember Data**
Loading screens blow. I downloaded the data. I shouldn't have to keep going to the server to get it again. You are probably using HTTP caching, but that still creates network requests. Getting good performance means cutting down on network requests. It's not very complicated to do in Backbone. Ember data should support local storage by default. For example, you create your store and you can set storedLocally: false if you don't want it stored. I think that adding local storage to support to the framework and enabling it by default would be a major win. Our app is dealing with a lot of data. Loading in data takes time and reduces performance. We only want to download that data once.
Issue for this single point here: https://github.com/emberjs/rfcs/issues/256

- **Ambitious Addition - Handling Bad Connections and Crashes: Gateway to Offline Support**
Network connections go down. Browsers crash. These things happen. We have the tools to make applications failure resistant. Let's take your basic todo list application. The user adds a todo and for some reason the server is down. What happens? Do we just say "opps, sorry. Please try again." I don't think so. The framework itself can handle these cases. Here is a proposed solution. Use a messaging queue backed by local storage to buffer requests to the backend API. Requests that match a set of failure conditions (503, 504, or timeouts) are enqueued again and will be tried again later. This is a step towards offline support at the data layer. There has been some discussion about this. There are few things in the way. A request/operation object needs to introduced. This object is persisted in the queue. The adapter takes the request objects then does whatever logic is needed and sends them to the server. These objects would need to be tied to records as well. Since operations to individual records are being tracked, this means you can cancel operations to specific records. There are also race conditions. Hell, there are lot of complicated things to worry about, but solving this problem is massive. Imagine if applications simply got support for this by using Ember. Boom, your application has some level of fault tolerance and it may even save you a few customers. I'd say this is hardest problem to work on but the pay off is fantastic.
Issue for this single point here: https://github.com/emberjs/rfcs/issues/257

**Maybe I'm wrong, but is there a way today to handle these problems?**

**Comment by johnunclesam** [comment]
- OFFLINE LAYER (maybe IndexedDB) in browser.
- ONLINE LAYER (My API backend server)
- SYNC (when I want or on online/offline check), replay history of PUT, GET, PATCH, EVERYTHING in server and maybe server can throw(error).

**Comment by luxferresum** [comment]
[Related thread in `discuss.emberjs.com`](https://discuss.emberjs.com/t/ember-issues-since-2012-maybe-is-there-a-way-today-integrating-push-to-keep-client-data-in-sync-local-storage-support-handling-bad-connections-and-crashes-gateway-to-offline-support/13633)

**Comment by courajs** [comment]
@johnunclesam I have separate thoughts on all three of these, but I don't think we want all that discussion interleaved in one thread. Could you open separate issues for each?

**Comment by johnunclesam** [comment]
Ok @courajs. I will open one for each of them.

**Comment by locks** [comment]
Closing this issue for the separate ones, thank you!
