### ISSUE TITLE
Integrating Push to Keep Client Data in Sync

### ISSUE THREAD

**Issue by ghost** [emberjs/rfcs#255]
I found this post from 2012 http://hawkins.io/2012/07/ember_wish_list/.

Since then something is changed, but not this point:

**Low Hanging Fruit - Integrating Push to Keep Client Data in Sync**
All complex applications allow data manipulation outside of user interaction. I mean not all data changes are done by users sitting on there devices. The server may be syncing something in the background which brings in new data. How is the client going to know about it? Is it periodically polling the server? That's crazy. It's easy to write code that pushes all changes. It should be equally easy to push that data into data store regardless of what push service you're using. Ember-data stores should define a simple interface to accept messages over push. Perhaps, the store itself is a web socket client which can be connected to your push stream. There are many different ways to do this. Everyone will solve this uncomplicated problem in the same way. This is exactly why the framework should do it. Ideally, there should be no problems if you switch from Websockets/Pusher/Faye/PubNub/Boxcar/etc. The messages always arrive.

All points here: https://github.com/emberjs/rfcs/issues/254

**Comment by mkay581** [comment]
I understand the concern but I'm unsure of how Ember could make a solution for this without considering the capabilities of the server which is serving the data. The server would need to support pushing data, which can be done in many different ways. How do you see Ember being able to implement a solution for all servers + configurations?

Regardless, though, I've always thought it beneficial that client-side frameworks like Ember not be concerned with backend/server implementation details and it would seem odd if they did.

**Comment by topaxi** [comment]
Synchronizing is something pouchdb does well and an addon exists already: https://github.com/pouchdb-community/ember-pouch

**Comment by johnunclesam** [comment]
@topaxi maybe you have never used what you advise. It does not solve what we are talking about in this issue. Sorry.
