### ISSUE TITLE
Handling Bad Connections and Crashes: Gateway to Offline Support

### ISSUE THREAD

**Issue by ghost** [emberjs/rfcs#257]
I found this post from 2012 http://hawkins.io/2012/07/ember_wish_list/.

Since then something is changed, but not this point:

**Ambitious Addition - Handling Bad Connections and Crashes: Gateway to Offline Support**
Network connections go down. Browsers crash. These things happen. We have the tools to make applications failure resistant. Let's take your basic todo list application. The user adds a todo and for some reason the server is down. What happens? Do we just say "opps, sorry. Please try again." I don't think so. The framework itself can handle these cases. Here is a proposed solution. Use a messaging queue backed by local storage to buffer requests to the backend API. Requests that match a set of failure conditions (503, 504, or timeouts) are enqueued again and will be tried again later. This is a step towards offline support at the data layer. There has been some discussion about this. There are few things in the way. A request/operation object needs to introduced. This object is persisted in the queue. The adapter takes the request objects then does whatever logic is needed and sends them to the server. These objects would need to be tied to records as well. Since operations to individual records are being tracked, this means you can cancel operations to specific records. There are also race conditions. Hell, there are lot of complicated things to worry about, but solving this problem is massive. Imagine if applications simply got support for this by using Ember. Boom, your application has some level of fault tolerance and it may even save you a few customers. I'd say this is hardest problem to work on but the pay off is fantastic.

All points here: https://github.com/emberjs/rfcs/issues/254

**Comment by mydea** [comment]
Having implemented a cordova & ember based app that needed to support full offline capabilities, I highly doubt that there is a generalized way to do this. This just depends a lot on multiple factors, like:

* How can the API handle this?
* Do you even want to retry or similar?
* Can you even retry? What if an action NEEDS to finish before something else can happen?
* ...

Overall, I think that there are surely some things that can be done via addons, but at the end this will always be an application concern as to how exactly to implement this.

Fyi, we have created https://github.com/mydea/ember-indexeddb for exactly this purpose. It provides an Ember Data Store based on IndexedDB that can be used. However, you need to manually push the data into the store - the way it works is that we always work of local data, and handle syncing that data in a separate service in our application.

**Comment by johnunclesam** [comment]
What we need is exactly the syncing part of the framework. What is in ember-pocuch but without the Pouch/Couch system, just the APIs.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
