### ISSUE TITLE
defineProperty incorrectly documented

### ISSUE THREAD

**Issue by annaemu** [emberjs/rfcs#258]
The documentation states this is correct:
`import { defineProperty } from "@ember/polyfills";`

However this results in a 
`@ember/polyfills does not have a defineProperty import`
error in ember 2.15 and based on https://github.com/ember-cli/ember-rfc176-data/issues/12 it should instead be (which works):
`import { defineProperty } from "@ember/object";`

**Comment by buschtoens** [comment]
Can you post a link to the erroneous part of the docs? :slightly_smiling_face:

**Comment by annaemu** [comment]
Sure, the references are in here:
https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md

**Comment by buschtoens** [comment]
Ah, so you're referring to the original RFC 176. I thought you meant the Ember guides. :smile:

**Comment by annaemu** [comment]
Sorry, I should have included the link earlier!

**Comment by buschtoens** [comment]
No problem. :wink: 

If you can spare the time, feel free to open a PR against the RFC to fix that.

**Comment by locks** [comment]
Thank you for the issue, however I don't think it is necessary to amend the RFC at this point. There are other cases of mismatch, or missing APIs that were added I believe, but the RFC isn't normative (the actual implementation doesn't need to completely follow or be limited to the RFC) and the source of truth is https://github.com/ember-cli/ember-rfc176-data.
We are keeping a watchful eye and hope the transition to the new modules with 2.16 has minimal impact for our users!
