### ISSUE TITLE
Placeholder: auto-parameterizing link-to / transitionTo

### ISSUE THREAD

**Issue by machty** [emberjs/rfcs#269]
See this [twitter discussion](https://twitter.com/machty/status/922889628163690497) for more details, but TL;DR the ability to directly pass a model to link-to / transitionTo _may_ be foot-gunny anti-pattern that could possibly be addressed by an API whereby all models passed to link-to / transitionTo() are parameterized (e.g. converted to numeric/string IDs) so that the `model` hook is still invoked.

The problem with today's behavior is that it makes it really easy to forget to implement a model hook for when the page is reloaded from URL, because the `model` hook is skipped when models are directly passed. It is also very confusing to teach/explain the sequence of hooks that are called given this subtle divergence in behavior, and if, in the future, all models were parameterized, we could theoretically condense all `beforeModel/model/afterModel` hooks into One True Hook™. 

So this is a placeholder issue to remind me / anyone that hopefully this idea will turn into a full blown RFC.

**Comment by buschtoens** [comment]
Would the `model` hook (or methods called inside it, e.g. `store.findRecord`) be responsible for determining whether and how to reload a parameterized model? I could imagine that many users would dislike it, if their apps all of a sudden start reloading data for route transitions that didn't do so before.

**Comment by ryanto** [comment]
I opened a PR for this here: https://github.com/emberjs/rfcs/pull/283

It's just a brain dump, but let me know if you want me to add more examples.

**Comment by wagenet** [comment]
Closing since there's a related RFC.
