### ISSUE TITLE
Deprecate `Function.prototype.{on,observes,property}`

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#271]
Ember has been moving away from extending native prototypes due to the confusion that this causes users.
The most recent case of this was part of the [`Ember.String` deprecation RFC](https://github.com/emberjs/rfcs/blob/master/text/0236-deprecation-ember-string.md), where the package was extracted and prototype extensions moved to a support addon.

To continue on this path, deprecation `Function.prototype.{on,observes,property}` should be investigated.
They have non-extension equivalents, both in the `import Ember from 'ember';` and `import { … } from '@ember/…'`.

**Comment by sarupbanskota** [comment]
I'll take this up

**Comment by locks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sarup Banskota](https://trello.com/c/IHNuZLNK/5-sarup-banskota)

**Comment by locks** [comment]
It is ddoonnneee. Thank you @sarupbanskota!
