### ISSUE TITLE
Handle sorting null values using computed.sort

### ISSUE THREAD

**Issue by jvenezia** [emberjs/rfcs#288]
It would be handy to choose how to sort "nulls".
Similar to SQL's `order by ... nulls last`

Something like this: 

```
  notesSorting: ['createdAt:asc:nullsLast'],
  sortedNotes: computed.sort('notes', 'notesSorting')
```

Right now `asc` put them at the beginning, and `desc` at the end.

wdyt?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
