### ISSUE TITLE
RFC: Sibling dynamic segment subroutes and static routes

### ISSUE THREAD

**Issue by linearza** [emberjs/rfcs#299]
I am not quite sure of the technical limitations and/or implications of such a change, but we ran into a scenario recently where we needed two subroutes, one with a dynamic segment (the model id) 
 with more subroutes below it and the other as just a static subroute (a sibling to the dynamic segment). For argument's sake we wanted a `task/:task_id` as well a `task/new` route.

Now I am aware that one can simply create seperate routes and set the path param so that they appear nested, like:

```js
this.route('task', { path: '/task/:task_id' });
this.route('task', { path: '/task/new' });
```

However the downside this this is that it doesnt run through the same route hierarchy setup, the same sequence of beforeModel, afterModel etc., which in our case we were dependent on for some logic around the nested subroutes within `/task/:task_id/subroute` as well as `task/new`. We basically to some setup, checking and routing on the parent `task` route.

So that all being said, is there any value in maybe adding the ability to nest dynamic segmented routes, alongside static routes for this reason? Something like:

```js
this.route('trip', {
  path: '/trip/:trip_id'
}, function() {
  this.route('index', {
    path: ''
  }, function() {
    this.route('subroute');
  });
  this.route('another-subroute');
}, {
  this.route('new');
});
```

**Comment by linearza** [comment]
Interesting! I will try that quick, but if this is indeed the solution then maybe it should just be clarified in the docs a bit, and maybe there is a better syntactical implementation for it, since it could potentially get quite hairy with multiple of these:

```js
this.route('task', { path: '/task/new' });
this.route('task', { path: '/task/edit' });
this.route('task', { path: '/task/delete' });
this.route('task', { path: '/task/:task_id' });
```

**Comment by buschtoens** [comment]
What about this?

this.route('tasks', { path: 'task' }, function() {
  // this.route('index'); // tasks/index/route.js
  this.route('new', { path: 'new' }); // tasks/new/route.js
  this.route('task', { path: ':id' }, function() {} // tasks/task/route.js
    this.route('edit'); // tasks/task/edit/route.js
    this.route('delete'); // tasks/task/delete/route.js
  });
});

**Comment by linearza** [comment]
Ive tried your first suggestion, but it doesnt seem to work for me, when trying to access `task/new` the router only resolves to `task` and errors out on the handlerInfo. When trying to access `task/:task_id` it resolves to the route initially but then also breaks somewhere before transitioning to `index` - there might be some local code at play here, so its worth recreating and confirming this behaviour in a clean app

**Comment by linearza** [comment]
Your second suggestion is viable, though we need access to the tasks route as well, as an example, we need access to all of these routes:

```js
this.route('task', {
  path: '/task/:task_id'
}, function() {
  this.route('index', {
    path: ''
  }, function() {
    this.route('save');
    this.route('enquire');
  });
  this.route('info');
});

// and this one
this.route('task', {
  path: '/task/new'
});
```

**Comment by buschtoens** [comment]
I don't really understand what you mean by 'need access to the tasks route as well'. All routes from https://github.com/emberjs/rfcs/issues/299#issuecomment-360734698 should 'accessbile'. These are the URLs:

```js
this.route('tasks', { path: 'task' }, function() {
  // this.route('index'); // /task
  this.route('new', { path: 'new' }); // task/new
  this.route('task', { path: ':task_id' }, function() {
    // this.route('index'); // /task/123
    this.route('edit'); // /task/123/edit
    this.route('delete'); // /task/123/delete
  });
});
```

**Comment by linearza** [comment]
In the above comment, what happens if I go to `/tasks`?

**Comment by buschtoens** [comment]
There is no `/tasks` route. You could change the top-level path to `tasks` though. Updated URLs:

```js
this.route('tasks', { path: 'tasks' }, function() {
  // this.route('index'); // /tasks
  this.route('new', { path: 'new' }); // tasks/new
  this.route('task', { path: ':task_id' }, function() {
    // this.route('index'); // /tasks/123
    this.route('edit');     // /tasks/123/edit
    this.route('delete');   // /tasks/123/delete
  });
});
```

**Comment by buschtoens** [comment]
If you definitely want to display all tasks as `/tasks`, but a singular task as `/task/123` you need to split it up like: 

```js
this.route('tasks', { path: 'tasks' }, function() {
  // this.route('index'); // /tasks
  this.route('new', { path: 'new' }); // tasks/new
});

this.route('task', { path: 'task/:task_id' }, function() {
  // this.route('index'); // /task/123
  this.route('edit');     // /task/123/edit
  this.route('delete');   // /task/123/delete
});
```

**Comment by linearza** [comment]
Thats the thing though, sorry if im going around in circles, but we need the routes:
/tasks

/task/:id
/task/:id/subroutes
/task/new

This is because of a presentational requirement, and the way our nested routes get displayed in the parent, so /new needs to be there.
So in our case tasks is actually a seperate listing route. We have quite a mature app that has the structure I pointed out above, and moving around existing routes isnt really viable at this stage, but I agree that when starting a fresh app and considering this that your implementation could be a solution, its just not in our case. 
So I also realise that we're trying to bend Ember to fit our structure, rather than structuring our app around these routing structure possibilities, nevertheless, I wonder if it can't be of value to have this dynamic+static sibling option as well?

**Comment by buschtoens** [comment]
> /tasks
>
> /task/:id
> /task/:id/subroutes
> /task/new

```js
this.route('tasks'); // /tasks

this.route('new', { path: 'task/new' }); // /task/new

this.route('task', { path: 'task/:task_id' }, function() {
  // this.route('index'); // /task/123
  this.route('edit');     // /task/123/edit
  this.route('delete');   // /task/123/delete
});
```

Does that solve your problem?

**Comment by linearza** [comment]
Yep, the above also works, the downside is that it isnt nested, and so doesnt run through the parent route hooks (beforeModel, afterModel etc) along with its siblings - but it is the solution if you can work around that

**Comment by nightire** [comment]
Actually Ember can do what you want surprisingly:

```javascript
  this.route('tasks');  // separate listing

  this.route('task', function() {  // provide `/task` base url
    this.route('new');  // provide `/task/new`
    this.route('index', { path: ':id' }, function() { // provide `/task/:id`
      this.route('subroute'); // provide `/task/:id/sub-routing`
    });
  });
```

In reality this generates something like below:

![image](https://user-images.githubusercontent.com/1104018/35441957-6c160db2-02e0-11e8-9cdc-c3ecb63f1813.png)

and I made a quick demo to test them by using:

```htmlbars
{{link-to "Tasks" "tasks"}}

{{link-to "New Task" "task.new"}}

{{link-to "Task 1" "task.index" 1}}

{{link-to "Do Stuff with Task 1" "task.index.subroute" 1}}
```

it turns out works very well.

**Comment by linearza** [comment]
@nightire - This sir, is exactly what I was looking for - as simple as moving the :id to the index route. Thank you very much!
