### ISSUE TITLE
Deprecate `Component#isVisible`

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#303]
Part of the [deprecations initiative](https://github.com/emberjs/rfcs/projects/1).

**Comment by Parrryy** [comment]
Looking into this as a potential RFC to do.

**Comment by rwjblue** [comment]
Sounds great! What can we do to help?

**Comment by Parrryy** [comment]
Any discussions with regards to deprecating this issue etc so i can get some research would help.

**Comment by Parrryy** [comment]
Any issues or discussions behind potential rational with regards to deprecating or issues it's causing would be helpful.

**Comment by rwjblue** [comment]
The RFC for this is in FCP (#324), so I'm going to close this...
