### ISSUE TITLE
Allow passing a function as the key for {{each}}

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#306]
Currently, `{{each}}` in templates have a `key` property that receives a string, which Ember sets for you using `guidFor`.

The `key` property only supports passing a string at the moment, but it would be useful to enhance it to also receive a function.
This function would have to be provided either by the current context (controller or component), or generated by a helper, like happens nowadays with `action`.

**Comment by rwjblue** [comment]
https://github.com/emberjs/rfcs/pull/321 addresses this...

**Comment by wagenet** [comment]
Closing since there's a related RFC.
