### ISSUE TITLE
Add a helper for the select box

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/rfcs#310]
How about an in-built helper to allow binding and initialisation of HTML SELECT boxes.
Why make people rely on add-ons for what is such a basic thing?

**Comment by ro0gr** [comment]
There are [lots of addons](https://emberobserver.com/?query=select) for select box already.

Actually I'd be happy if one day existing form element helpers([input](https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers/methods/textarea?anchor=input), [textarea](https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers/methods/textarea?anchor=textarea)) will be removed as ember built-ins. From my personal experience they cause more issues than benefits(2 way data binding by default, custom event names, not all attributes are supported out of the box). It ussually can be replaced by vanilla `<input` and `<textarea` tags.

**Comment by ro0gr** [comment]
Also the big issue with this kind of "helpers" is that seems like it's actually neither a helper(regular helper doesn't output DOM and doesn't have events) nor component(regular component can be looked up via `{{component ` helper). So as a user I don't understand how does it really work.

**Comment by rwjblue** [comment]
> Actually I'd be happy if one day existing form element helpers(input, textarea) will be removed as ember built-ins. 

Totally agree.

**Comment by rwjblue** [comment]
FWIW, we did have a `{{select` component in Ember 1.x. It was much pain.

**Comment by Benjy1979** [comment]
Hi,

I'm not bothered at all about input and textarea. This is about Select because it has some awkwardness. 
Why is it anymore complicated than adding a built-in component that you don't have to use.
 
All I know is I just spent 3/4 hours or so faffing with a select box then eventually realising I needed to write my own component to do the job, ie {{my-select}} and {{my-option}}, binding the "selected" attribute, all the time wondering whether I'm doing it the right way and wishing it was already there.

**Comment by rwjblue** [comment]
It is **extremely** unlikely that we are going to be able to do a better job than ember-power-select, ember-basic-dropdown, emberx-select, etc. There really isn't a reason (that I can tell) for this to exist in core vs living in a community addon...

**Comment by Benjy1979** [comment]
I do have a slight prejudice against using third-party add-ons. Maybe this is something I have to address. But then ember.js is for ambitious apps, maybe it should mention only if you go hunting for add-ons by other people.

**Comment by rwjblue** [comment]
Ha! Ember is all about shared solutions to common problems, and addons are an awesome way to do this. It is extremely likely that if we had had addons at the time a non-trivial percentage of Embers existing API surface would have simply been left to addons.

**Comment by Benjy1979** [comment]
If ember-power-select is good and complete as said - which it is, having used it myself, then why not ship it out with the core then.
