### ISSUE TITLE
Deprecate {{with}} helper

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#316]
With the introduction of the [block `{{let}}` helper](https://github.com/emberjs/rfcs/blob/master/text/0286-block-let-template-helper.md), it is now possible to replace usages of `{{with}}`.
The reason to deprecate `{{with}}` is that the conditional behaviour of the block not being rendered when the first parameter to `{{with}}` is falsey is confusing to users.

To give an example, before:

```
{{#with parent.child as |child|}}
  {{child}}
{{else}}
  No children!
{{/let}}
```

After:

```
{{#let parent.child as |child|}}
  {{#if child}}
    {{child}}
  {{else}}
    No children!
  {{/if}}
{{/let}}
```

For convenience, an `if-let` helper could be proposed at a later stage.

**Comment by balinterdi** [comment]
What would this be replaced by? The `{{let}}` helper? Or would it be moved to an add-on?

**Comment by Panman8201** [comment]
@balinterdi Yep https://github.com/emberjs/rfcs/blob/master/text/0286-block-let-template-helper.md#deprecating-with

**Comment by kellyselden** [comment]
For someone using this effectively, what is their alternative?

```hbs
{{#let parent.child as |child|}}
  {{#if child}}
    {{child}}
  {{/if}}
{{/let}}
```

The above seems very ugly for someone who was happy with how `{{with}}` functioned.

**Comment by rwjblue** [comment]
@kellyselden - Conceptually, that is better referred to as `if-let`, and is absolutely a fine thing. `{{#with` is just a really bad name for that pattern...

**Comment by kellyselden** [comment]
@rwjblue My apologies, I didn't know that was a thing. That is a good replacement.

**Comment by rwjblue** [comment]
This just came up again at a core team call, I think we are all 👍 to adding `if-let` (with today's `{{with}}` semantics) and deprecating `{{with}}` itself. 

We would _love_ help with authoring the RFC from folks with time (and I am happy to champion with the broader group as needed)...

**Comment by GavinJoyce** [comment]
@rwjblue LMK if this is still available, I can author the draft RFC

**Comment by locks** [comment]
@GavinJoyce go for it! Thanks for the help 🙏
