### ISSUE TITLE
Add max() method to Class MutableArray

### ISSUE THREAD

**Issue by Caltor** [emberjs/rfcs#347]
Please can I have feedback on this idea. I would like to suggest that we add a `max()` method to the `MutableArray` class. This would allow us to easily get the maximum numerical value in an array.

So at the moment we have to do this:
```
  let result = array.reduce(function (a, b) {
      return Math.max(a, b);
  });
```

whereas this addition would let us do this instead:
`let result = array.max();`

I know it's not a massive saving but it all adds up and makes Ember more complete and user-friendly. I can't imagine it is a lot of work to add this either.

P.S. I am completely new to this process so please don't kick me too hard if I get it wrong!

**Comment by davewasmer** [comment]
@Caltor thanks for the suggestion! This looks like the right process to me - getting feedback before submitting a full fledged RFC is a good idea.

I'd suggest that this doesn't belong in Ember core though. While it might be nice to have in certain circumstances, it doesn't really directly relate to the core problems Ember addresses. It can be tempting to make Ember provide solutions for every possible use case, but each bit of code we add to the framework is code that has to be maintained over time.

There's also really good libraries out that there provide a lot of these utility functions already. For example, lodash ships with a `max()` method that does exactly this. I'd suggest we point folks to using those kinds of solutions for these scenarios.

**Comment by Caltor** [comment]
@davewasmer Thanks for the vote of confidence on the process!

I understand your reasoning on this. My question in turn would be; using your rationale, what is the justification for the existing methods of MutableArray such as `reduce`, `map`, `find` etc? Do these directly relate to the core problems Ember addresses and what are the stated core problems? Aren't these methods already provided by JS itself or third-party libraries such as lodash?

I'm not being (completely) nowty; I'm just trying to understand the rationale better and engage in a bit of healthy debate. 😁

**Comment by rwjblue** [comment]
> My question in turn would be; using your rationale, what is the justification for the existing methods of MutableArray such as reduce, map, find etc? Do these directly relate to the core problems Ember addresses and what are the stated core problems? Aren't these methods already provided by JS itself or third-party libraries such as lodash?

Yes, this is exactly why we 1) probably don't want to _increase_ surface area and 2) are working to make a migration path **off** of things like `MutableArray` / `Enumerable` / `ArrayProxy` / etc (in favor of "just use JavaScript")...

**Comment by Caltor** [comment]
Gotcha! 👍

**Comment by buschtoens** [comment]
```js
const maxValue = Math.max(...array);
```

🧙

**Comment by Caltor** [comment]
@buschtoens That is awesome. I always forget about the rest/spread operator.
