### ISSUE TITLE
Declare Ember.defineProperty as public?

### ISSUE THREAD

**Issue by simonihmig** [emberjs/rfcs#350]
I am opening this here for discussion, as I have seen confusing statements (to me at least) in other repos/issues, so would like to clarify this here in a central place...

## Problem

`Ember.defineProperty` is declared private, although it seems to be widely used in the wild (see below). IMHO there is at least one valid use case for it, when the dependent keys of a CP are not known it advance.

## Status quo
* used in addons where the dependent keys are not known in advance. Examples: 
  * https://github.com/offirgolan/ember-bootstrap-cp-validations/blob/7a85bf27796d2ac62a57d5b6a236c888fc102916/addon/components/bs-form/element.js#L23 (cc @offirgolan)
  * emberobserver.com finds [201 addons](https://emberobserver.com/code-search?codeQuery=defineProperty) containing `defineProperty`. Admittedly that also includes usage of `Object.defineProperty`, but a quick scan suggested a significant use of `Ember.defineProperty` as well!
* mentioned in blogs/other media. Examples:
  * http://mcdowall.info/an-experiment-in-refactoring-ember-properties/
  * https://stackoverflow.com/questions/38970530/creating-alias-to-a-dynamic-property-now-that-ember-binding-is-deprecated
* mentioned in an official deprecation guide: https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object (which kicked off this discussion I believe, see https://github.com/emberjs/ember.js/issues/16790)
* named export in RFC176 data: https://github.com/ember-cli/ember-rfc176-data (which only makes sense when considered public, right?)

## Opinions

* @ef4 suggested on Slack recently, that it should remain private. The relevant transcript can be found in this issue: https://github.com/ember-learn/deprecation-app/issues/157
* @rwjblue's [comment](https://github.com/emberjs/ember.js/pull/16791#issuecomment-403477332) suggests making it public (if I read it correctly)
* my own personal take: the use case of declaring CPs with dynamic dependent keys would justify making this public (FWIW, I always considered it public, without checking 🤨). The solution offered by @ef4 (see link above, third bullet point) seems pretty inconvenient for this IMHO valid use case.

/cc @jenweber @ef4 @rwjblue

**Comment by simonihmig** [comment]
> it should be marked as public

would that require a full-blown RFC process?

**Comment by rwjblue** [comment]
IMHO, no (it would just require a PR to change the docs from `@private` to `@public`), but it is something that we (the core team) should generally agree on before doing. 

I'll try to take this to the next core team meeting to confirm we have consensus...

**Comment by buzzware** [comment]
While the wind seems to be blowing towards static/explicit typing, I hope that Ember continues to provide "sharp knives" like this to enable meta-programming and other dynamic approaches.
