### ISSUE TITLE
[FEAT] `hasMany` and `belongsTo` requests should use adapter `findHasMany` and `findBelongsTo` hooks

### ISSUE THREAD

**Issue by runspired** [emberjs/rfcs#356]
Previous Discussions:

- https://github.com/emberjs/rfcs/pull/266
- https://github.com/emberjs/data/issues/2162

`findHasMany` and `findBelongsTo` would delegate to `findMany` and `findRecord` as they do today in the case where there is no link present, to preserve existing behavior while simplifying the overall flow and enabling this case to be handled.

**Comment by mydea** [comment]
I created an RFC to tackle this issue: https://github.com/emberjs/rfcs/pull/387

**Comment by wagenet** [comment]
Closing since there's an associated RFC.

**Comment by wagenet** [comment]
Note that this RFC was not merged.

**Comment by runspired** [comment]
The `request` manager replaced this.
