### ISSUE TITLE
[FEAT] `root.deleted.empty` state 

### ISSUE THREAD

**Issue by runspired** [emberjs/rfcs#358]
Currently records whose deletion is persisted that are then unloaded transition into `root.empty` prior to being purged from the store. This results in odd behaviors when a user has retained a reference to the record that could be guarded against if we consider this `empty` state to be different from `root.empty` which is typically used for when an `InternalModel` is a reference to an unloaded remote resource.

**Comment by fivetanley** [comment]
@jmar910 and I will champion this one.

**Comment by runspired** [comment]
covered by #737
