### ISSUE TITLE
[FEAT] sortBy() should allow for sorting in DESC order.

### ISSUE THREAD

**Issue by abhishek97** [emberjs/rfcs#363]
Currently the only way to achieve a `DESC` sort is

`values.sortBy('prop').reverse()`
Or 
`values.sortBy('negProp')` , where `negProp` is a computed property which negates the value of `prop`.

Looking at the source, it is easy to add this functionality, I can send in a PR if we can agree on API.

I propose some examples:

`values.sortBy('-prop')` : the `-` means desc order
`values.sortBy('prop', {
   order: 'desc'
})`

**Comment by mehulkar** [comment]
sortBy (and its friends) should probably just end up getting removed

**Comment by abhishek97** [comment]
I think i might have missed that in the docs. computed.sort() will work. 

However i dont think sortBy should be removed.

**Comment by locks** [comment]
Closing as no longer relevant since the project is moving towards tracked properties.
