### ISSUE TITLE
Pre-RFC: Deprecate partials

### ISSUE THREAD

**Issue by tomdale** [emberjs/rfcs#390]
Partials are widely believed to be a bad idea, but we don't do enough to help people understand that they should *always* prefer a component to a partial.

We should deprecate partials in Ember, ideally as part of Octane. I believe the only thing blocking this currently is the lack of a deprecation RFC. We may also want a code mod that can automatically migrate the most common partial cases, although I'm not sure if I'd want to block deprecation on that.

**Comment by rwjblue** [comment]
>  We may also want a code mod that can automatically migrate the most common partial cases, although I'm not sure if I'd want to block deprecation on that.

I would like to see a codemod mentioned in the deprecation RFC, but I don't think we need to hold up work on implementing the deprecation for any codemod work...

**Comment by knownasilya** [comment]
Would https://github.com/dyfactor/dyfactor be the tool for that? I know it's still young, but I think it could handle all partial migrations if done right.

**Comment by ctcpip** [comment]
@lbeauvilliers it's happening

**Comment by lbeauvilliers** [comment]
@ctcpip 😱

I mean ...  🎉

**Comment by webark** [comment]
parsing the partial for all variables, and passing all those into a component seems like a harry task for a codemod..

**Comment by rwjblue** [comment]
You say hairy, I say fun 😜

**Comment by Alonski** [comment]
So just chiming in that after upgrading to Ember v3.7 I am seeing a regression related to Partials that is causing an error in my app.
I am all for deprecating partials!

**Comment by rwjblue** [comment]
@Alonski - You might want to report that over on emberjs/ember.js, we haven't intentionally broken anything related to partials...

**Comment by GavinJoyce** [comment]
Is there anything blocking the initial RFC from being created? If not, and it suits, I'd like to volunteer to author the RFC and then help implement the changes needed if it lands.

**Comment by rwjblue** [comment]
Nope, nothing blocking other than needing someone to work on it. 😸

**Comment by GavinJoyce** [comment]
👍 thanks, I'll draft an RFC soon

**Comment by GavinJoyce** [comment]
Here's the RFC to deprecate `{{partial}}`s: 

https://github.com/emberjs/rfcs/pull/449

**Comment by ngouy** [comment]
the idea of a "kind of component" having the same context as the parent was sometimes very helpfull : 
https://blog.nathangouy.com/emberjs-full-component-inheritance/

I don't pretend this stuff is good practices and good patterns/design, but still, without partials, we have to pass all attributes tu the called component. I guess it will be easier with the new `...` syntax (I am not sure but I think I saw something like that in the pipes ?)

**Comment by mydea** [comment]
Not sure how "best practice" that is, but you _can_ pass `this` to a component, e.g.:

```hbs
{{! app/components/item.hbs }}
{{item-child parent=this}}
```

```hbs
{{! app/components/item-child.hbs }}
{{parent.title}}
```

Use with care, but can be useful for some tricky edge cases.

**Comment by ngouy** [comment]
1 - Not sur it is ^^
2 + in my above exemple, the idea it to have inheritance. In inheritance patern, you don't have to call parent.property when you are accessing smt that "belongs to" your inherited parent

**Comment by rwjblue** [comment]
Closing in favor of #449
