### ISSUE TITLE
[DATA] Deprecate exports of managed classes

### ISSUE THREAD

**Issue by runspired** [emberjs/rfcs#400]
The following classes only function properly when they are instantiated as classes managed by the store. We should deprecate public import access to them for this reason. Where necessary, APIs should be created to enable creation of managed instances for tests as appropriate (see #396 for an example of one that needs this).

- `DS.PromiseManyArray`
- `DS.ManyArray`
- `DS.Snapshot`
- `DS.PromiseArray`
- `DS.PromiseObject`
- `DS.RecordArray`
- `DS.AdapterPopulatedRecordArray`
- `DS.RecordarrayManager`
- `DS.Relationship`

- (some folks have used) `DS.Errors`
- (private but intimate) `DS.InternalModel`
- (private but intimate) `DS.RootState`

**Comment by mydea** [comment]
Not sure, but we do use `PromiseObject` and `PromiseArray` in our apps. 
As an example usage, there are places where we build "fake relationships" with computed promises, like this:

```js
export default Model.extend({
  ajax: service(),
  name: attr(),
  fakeRelationship: computed('id', function() {
     let promise = this.ajax.request(`/my-special-endpoint/${this.id}`);
     return PromiseArray.create({ promise });
  })
});
```

This way, we can use this in our app the same way as all other relationships, and do not need to know which relationships are "real" and which aren't - which is nice, and allows us to easily switch them with "real" relationships if the API changes or similar.

**Comment by runspired** [comment]
Covered by #743
