### ISSUE TITLE
[OCTANE] Craft Glimmer Component RFC

### ISSUE THREAD

**Issue by MelSumner** [emberjs/rfcs#405]
This RFC should include: 
- Defining the base class
- Where it will be imported from
- How will Ember/Glimmer interop work

This issue is part of the [Octane Edition](https://github.com/emberjs/ember.js/issues/17234) of Ember.js.

**Comment by bartocc** [comment]
isn't this done by #416 ?

**Comment by rwjblue** [comment]
Yep, thank you @bartocc!
