### ISSUE TITLE
Add setupApplicationTest helper file to blueprints

### ISSUE THREAD

**Issue by iezer** [emberjs/rfcs#413]
Not sure if this needs to be an RFC but I'd like to start the issue here. I'd like to propose changing the Ember app blueprints to create a new file:

```js
// tests/helpers/setup-application-test.js
import { setupApplicationTest } from 'ember-qunit';

export default function(hooks) {
  setupApplicationTest(hook);
}
```

And change the Acceptance Test blueprint:

```js
// BEFORE
import { setupApplicationTest } from 'ember-qunit';

// AFTER
import setupApplicationTest from '[APP_NAME]/tests/helpers/setup-application-test';
```

It's common to have to do this in Ember apps when there are additional steps that have to be performed for all acceptance tests.

I also propose doing something similar for `setupRenderingTest`.

Thoughts?

**Comment by rwjblue** [comment]
FYI - I transfered this over to emberjs/rfcs for tracking as a feature request.

**Comment by locks** [comment]
We're finally there! https://github.com/ember-cli/ember-new-output/blob/v4.3.0/tests/helpers/index.js
