### ISSUE TITLE
Can ember computed recieve the computed properties as arguments to the resulting function?

### ISSUE THREAD

**Issue by sonic1981** [emberjs/rfcs#429]
I find myself writing this code a lot:

```
mycomputed:computed('model.myvalue', function(){
        let myvalue= this.get('model.myvalue');
        ....
    })
```

this always seems a bit long winded to me. It'd be great if the computed helper automatically grabed what I was listening for, something like:

```
mycomputed:computed('model.myvalue', function(model_myvalue){
        ....
    })
```

saving me the `let`..`this.get`..etc. call(s). In this example it's trivial, but the overhead of adding multiple `computed` and writing the same `this.get` code over and over does add up.

Thoughts?

**Comment by Dave-Choi** [comment]
I've thought something like this would be nice before.  I've got some reservations about removing the option to set these as consts or whatever.  

Another edge case to think about is stuff like "posts.@each", or "posts.[]".  Would you pass the whole collection?  Just the changed elements?

**Comment by kellyselden** [comment]
With `@tracked` properties in the future, I don't think there will be any computed overhauls in the future. In the meantime, you can use https://github.com/kellyselden/ember-macro-helpers#computed if you prefer.

**Comment by sonic1981** [comment]
> With `@tracked` properties in the future, I don't think there will be any computed overhauls in the future. In the meantime, you can use https://github.com/kellyselden/ember-macro-helpers#computed if you prefer.

and what is a "tracked" property when it's at home?! :) A quick Google gives me an hour long video and some Glimmer stuff that I don't understand.

Ember could do with a little more evolution and a little less revolution.

**Comment by averydev** [comment]
@sonic1981 The discussion of tracked is right over here:
https://github.com/emberjs/rfcs/blob/2232b5bb325ab222079df395fb893cef92748ea0/text/0000-tracked-properties.md

If you happen to have already jumped into native class syntax via the awesome Ember Decorators add on, you can use this here to get the functionality you're looking for right now:
https://github.com/ember-decorators/auto-computed

**Comment by rwjblue** [comment]
I believe the path forward here is via auto-tracked properties also, take a look over in https://github.com/emberjs/rfcs/pull/410...

**Comment by tomdale** [comment]
@sonic1981 Closing this issue because we agree with the above thread that tracked properties will eliminate the problem and we believe are the future direction. Let us know if you have further questions/concerns.

**Comment by lifeart** [comment]
https://github.com/kellyselden/ember-macro-helpers#computed
