### ISSUE TITLE
Deprecate controller injection

### ISSUE THREAD

**Issue by mehulkar** [emberjs/rfcs#430]
Controllers can only be injected into other controllers. I haven't done this in a while other than to hack something together. I think we could get deprecate and remove this functionality.

**Comment by tomdale** [comment]
I agree that this functionality doesn't really make sense any more and comes from a time before we had services as a first-class concept.

My only question is, does it make sense to deprecate controller injection specifically, or wait to deprecate controllers as a whole? I believe the major blocker to removing controllers from the programming model is query params.

I think the answer to this depends on how common controller injection is in production apps. If it rarely happens and dealing with the deprecation is as simple as extracting the controller code into a service, that's reasonable. But if we cause people to need a major refactor, and then another major refactor if we deprecate controllers, it might be better just to wait and have people do it in one step.

**Comment by locks** [comment]
@chadhietala mentioned that controller injection is part of the suggested solution for moving off of the `Route` render methods. See the second example in https://github.com/emberjs/rfcs/blob/01af231ad8c1275424eba457f1241469d7b33b77/text/0418-deprecate-route-render-methods.md#transition-path.

**Comment by mehulkar** [comment]
@tomdale, valid point. Is writing the Rfc and waiting for comments the best way to gather this data? For what it’s worth, I think removing controller injections is a much smaller change in mental model than removing controllers altogether. Since components and services have been introduced, controller injection has always felt like an abuse of DI to me.

@locks that’s good to know, but I thought the refactor presented in that RFC could be taken a step further to remove the injection altogether; right now it attempts to preserve the template/controller combo, which requires injecting a controller, but I wouldn’t be surprised if renaming the controller to a service would “just work” in the example. Secondly, the example in that RFC injects a controller into a component, which I thought was illegal?

**Comment by mehulkar** [comment]
Opened #574 for this.
