### ISSUE TITLE
Feature Request : limit the number of simultaneous HTTP request

### ISSUE THREAD

**Issue by olivierchatry** [emberjs/rfcs#438]
In my software, I'm loading a lot of data at the same time through JSONAPI. All the request are made simultaneously, which overload the server, and end up timing out with a following adapter error. 

It would be nice to have a way to limit the number of concurrent request. I guess the  `adapter.ajax` function should be using a queue instead if directly send the query.

**Comment by averydev** [comment]
FWIW @olivierchatry take a look at [Ember Concurrency](http://ember-concurrency.com/docs/introduction/) and I think you'll get a lot of the functionality you're looking for here for free :)

Would that do the trick?

**Comment by runspired** [comment]
Adapters are user-land concepts and their implementations are specific to an application's needs. If your application requires limiting concurrent requests, implementing an adapter that does so (as you have done) is the correct way to approach this.

**Comment by olivierchatry** [comment]
Yes, info understand, but I think this is a fairly common an useful feature to have.

**Comment by locks** [comment]
Thanks for bringing this up. I think the approach you took is a good one, and I think the next step would be to make it available as an addon. I'm closing the request as this is something that should be done in user-land from the comment above, and it seemed like you had the necessary hooks to implement it. If you have the implementation in an addon that you can share, let the Ember Times team know!
