### ISSUE TITLE
Time to move back to NPM?

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/rfcs#448]
Yarn is great. Some would even say awesome. But NPM is too. The Ember community made a big move to yarn, much of which (IMHO) was driven by @wycats's working on the project and articles like https://yehudakatz.com/2016/10/11/im-excited-to-work-on-yarn-the-new-js-package-manager-2/ but a lot has happened in 2.5 years and NPM has made tremendous strides.  In fact:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I&#39;m really proud to have been a part of yarn, which has helped kick npm back in gear. I&#39;ve been using npm5 and it&#39;s great!</p>&mdash; Yehuda Katz 🥨 (@wycats) <a href="https://twitter.com/wycats/status/875402203518820352?ref_src=twsrc%5Etfw">June 15, 2017</a></blockquote>

It's easy to use either one in an app or project, but Yarn tends to be preferred by many projects because it is seen as the Ember Way™️. I think this is an area where Ember can get back on track with the larger ecosystem and move back to NPM. If core projects make this move addons and apps will follow.  NPM is still the default for new projects and with time some difficult to read switching code can be removed from `ember-cli` blueprints and moving between developing addons will no longer require `ls` to check what lockfile is available. Making this decision in a RFC signals a change in direction to the community and takes one more meaningless decision away when starting a new project.

Does Yarn provide something that NPM does not?

**Comment by runspired** [comment]
Fwiw I still have more success with yarn's lockfile than npm's, but both seem to be buggy still so it isn't much of a win :( 

I do have a better experience with yarn trying to work on projects offline.

**Comment by mehulkar** [comment]
I would reeeeeealllly love for Ember guides to at least provide a toggle for yarn or npm instructions. For someone who is perpetually out-of-date and likes copy paste, it's really tough to have to do a mental translation between yarn and npm.

**Comment by jrjohnson** [comment]
After some discussion on Discord I've been convinced that NPM is the default for Ember and all the documentation and blueprints so there is nothing to move back *from*. Most projects I'm involved with use yarn, but that is an individual decision. 

One of the most tangible benefits of choosing ember is the consistent developer experience and documentation that applies to every app. It is up to everyone to make the right choice for their environment. In some cases that will be yarn, but if you want your app to align with the docs then NPM should get your full consideration, it is the default and if you don't have a reason to choose yarn then go with NPM.

Officially Ember will always support the package manager shipped with [supported versions of node](https://github.com/nodejs/Release).

As for me, I'll be moving things I work with back to NPM.
