### ISSUE TITLE
Pre-RFC: change eslint blueprint

### ISSUE THREAD

**Issue by buschtoens** [emberjs/rfcs#450]
In our day-to-day usage of ember-cli, we have found the default eslint config included in the `app` and `addon` blueprints to be very brittle. When you add rules that are specific to Ember or frontend development they'll take effect for Node.js files as well. This leads to false positives.

You can combat these with:

- In-file comments, like `// eslint-disable-line`, `/* eslint-disable */`
- Completely ignoring some Node files by adding them to `.eslintignore`
- Disabling these rules again in the [`overrides` section](https://github.com/ember-cli/ember-new-output/blob/c2545c6090f38bb9981a2ceb88b75bab144b1066/.eslintrc.js#L19-L40)

I think that all of these solutions are not ergonomic, hard to maintain and error-prone. This is partially to blame on the insufficient options that the eslint config file format offers. They are aware of it and have an RFC for a new format: https://github.com/eslint/rfcs/pull/9

While all of this is still shaking out, we have taken a different approach for our internal apps and addons that I think works much better. Instead of `overrides`, we create multiple `.eslintrc.js` files that each are [`root: true`](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).

For instance, our eslint config for addons looks like this:

```
.
├── .eslintrc.js
├── addon
│   └── .eslintrc.js
├── app
│   └── .eslintrc.js
└── tests
    ├── .eslintrc.js
    └── dummy
        └── config
            └── .eslintrc.js
```

```js
// .eslintrc.js
module.exports = {
  root: true,
  extends: '@clark/node'
};
```
```js
// addon/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: '@clark/ember-typescript'
};
```
```js
// app/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: '@clark/ember'
};
```
```js
// tests/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: '@clark/ember-typescript'
};
```
```js
// tests/dummy/config/.eslintrc.js
module.exports = {
  root: true,
  extends: '@clark/node'
};
```

You can find a live example of this in:

- [`ember-dead-code`](https://github.com/buschtoens/ember-dead-code)
- [`ember-route-task-helper`](https://github.com/buschtoens/ember-route-task-helper)

#### Key Advantage

With this setup, there is no need for hard to maintain file lists in `overrides` any more. This also avoids having to re-disable frontend specific rules in the overrides.

#### Key Drawback

Adding custom rules is non-DRY. If I want to add rules for all Ember files, I need to add these rules in 3 different places. For us this has not been a problem yet, since we enforce a consistent code style and disallow customizations anyway.

For users that do not maintain their own eslint base configs they can extend from, this could become a problem though. An easy fix is referencing a project-local base file, like so:

```
.
├── .eslintrc.js
├── .eslintrc.ember.js
├── addon
│   └── .eslintrc.js
├── app
│   └── .eslintrc.js
└── tests
    ├── .eslintrc.js
    └── dummy
        └── config
            └── .eslintrc.js
```
```js
// .eslintrc.js
module.exports = {
  root: true,
  extends: '@clark/node'
};
```
```js
// .eslintrc.ember.js
module.exports = {
  extends: '@clark/ember',
  rules: {
    'a-custom-rule': 'error'
  }
};
```
```js
// addon/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: require.resolve('../.eslintrc.ember.js')
};
```
```js
// app/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: require.resolve('../.eslintrc.ember.js')
};
```
```js
// tests/.eslintrc.js
/* eslint-env node */
module.exports = {
  root: true,
  extends: require.resolve('../.eslintrc.ember.js')
};
```
```js
// tests/dummy/config/.eslintrc.js
module.exports = {
  root: true,
  extends: require.resolve('../../../.eslintrc.js')
};
```

This way all individual configs still reference the exact same base config, which makes adding customizations DRY again.

In our use case, this is actually disadvantageous, since we need slightly different base config flavors in the different directories. `addon` and `tests` are using TypeScript, but `app` cannot use TypeScript, since it is merged with the host app's `app` tree.

#### Migrating Existing Projects

Running `ember-cli-update` would add all the new `.eslintrc.js` files. The pre-existing root `.eslintrc.js` will get merge conflicts, if customizations have been made. We could add comments in the file to explain what's going on.

**Comment by buschtoens** [comment]
Side note regarding `/* eslint-env node */` in some `.eslintrc.js` files:

The configuration in any of the above `.eslintrc.js` files also takes effect for the file _itself_. Since our `@clarkapp/ember` base config sets the `browser` environment, the `module` global is undefined. By adding that comment, we let eslint know, that this _one_ file is actually a Node file.

Alternatives are:

- Adding `.eslintrc.js` to `.eslintignore`, but this would enable linting completely for these files.
- Adding `overrides` for `.eslintrc.js` to the file itself or to the base config they extend.
- Not using a `.js` format, but instead `.json`.

The general problem with `/* eslint-env node */` and `overrides` is still that all the other frontend specific rules take effect. In my experience so far, this has not been a problem though, since these config files should not contain a lot of logic in the first place. Ideally you package all of this up into shared base configs.

**Comment by rwjblue** [comment]
In general, I massively prefer the single root level `.eslintrc.js` file over many `.eslintrc.js` files sprinkled around the codebase. 🤔

**Comment by buschtoens** [comment]
It's 5 / 6 in total for addons and for apps it's just 2: one at the root for Node and one in `app` for Ember.

If we'd decide for the `.eslintrc.ember.js` approach to DRY it up by default, we could also add comments to the 3 files that reference the base file to explain that rules should only be added in said base file.

Alternatively, we could even symlink the files. I don't know how well this plays with Windows though.

I agree that _sprinkling_ different eslint configs throughout the project is a bad idea. But in this case we are not really sprinkling IMO.

Can you pinpoint the exact reasons which put you off? Maybe we can find solutions to these.

**Comment by locks** [comment]
@buschtoens @rwjblue hi hi! is this topic still relevant?

**Comment by NullVoxPopuli** [comment]
The 'overrides' approach i'm using in my 'eslint configs' i think solves this, and is still only one file

**Comment by wagenet** [comment]
I'm going to go ahead and close this. If this is still something that anyone wants to move forward, I will gladly reopen!

**Comment by NullVoxPopuli** [comment]
The approach I use here works for all my ember projects, JS, TS, Addons, V2 Addons, etc

https://github.com/NullVoxPopuli/eslint-configs

```js
// .eslintrc.js
'use strict';

const { configs } = require('@nullvoxpopuli/eslint-configs');

// accommodates: JS, TS, App, Addon, V2 Addon
module.exports = configs.ember();
```
