### ISSUE TITLE
Shorthand function literal in computed properties

### ISSUE THREAD

**Issue by adriancooney** [emberjs/rfcs#455]
Sometimes I find defining computed properties that do small computations a little clunky due to the full `function() { .. }` literal syntax. As a suggestion, could we pass the instance of the object as the first parameter to the `computed`'s callback to allow us to use the shorthand function literal syntax?

So instead of 

```js
  fullName: computed('firstName', 'lastName', function() {
    return `${this.firstName} ${this.lastName}`;
  })
```

We could do:

```js
  fullName: computed('firstName', 'lastName', person => `${person.firstName} ${person.lastName}`)
```

Or even shorter now that we have native getters:

```js
  fullName: computed('firstName', 'lastName', ({ firstName, lastName }) => `${firstName} ${lastName}`)
```

There should be no breaking API changes since the `computed`'s callback does not currently receive any parameters.

**Comment by artemgurzhii** [comment]
@adriancooney Please take a look at https://github.com/emberjs/rfcs/issues/429

**Comment by locks** [comment]
Given the general shift to auto-tracked properties, and the availability of the `@computed` decorator in native classes, I think the ergonomics have improved enough in this area.
Thanks for bringing up this idea!
