### ISSUE TITLE
`hasBlock` deprecation, documenting `(has-block` and `(has-block-params`

### ISSUE THREAD

**Issue by mixonic** [emberjs/rfcs#469]
In working on Octane documentation I realized the following:

* `hasBlock` behaves as a keyword in templates, still exists
* `(has-block` is a helper which was added intending to replace `hasBlock`. It is suggested in the guides as best practice but has no API documentation as an Ember helper.
* `(has-block-params` is often mentioned by VM developers when `(has-block` is being discussed, however this is also not documented as a public API.
* AFAICT there has been no RFC that got us here

I'd like to propose an RFC which would resolve this loose end:

* RFC would document/describe the `(has-block` API, including use for inverse blocks.
* RFC would document/describe the `(has-block-params` API, including use for inverse blocks.
* RFC would require that we document the same as API.
* RFC would propose and document a deprecation for `hasBlock`

This is related to https://github.com/emberjs/rfcs/pull/460 (@wycats on named blocks) as I believe these APIs will have a lot more use and prominence once named blocks land.

**Comment by knownasilya** [comment]
Looks like the documentation has been updated here https://github.com/emberjs/ember.js/pull/17767

**Comment by MariannaAtPlay** [comment]
Hello,
has `hasBlock` been deprecated?
Trying to understand the difference btw `hasBlock` and `has-block`.

**Comment by knownasilya** [comment]
It hasn't, but should be. From a user's perspective it seems like there is no difference.

**Comment by wycats** [comment]
@knownasilya that is correct. @rwjblue should we open a deprecation RFC? Or is there already one?

**Comment by chancancode** [comment]
I think we may not want to touch this while we are working towards template imports? While I do think this will stay a keyword and doesn't make sense to import it, having everything else in `camelCase` while keeping this in `d-a-s-h` may be strange.

**Comment by wycats** [comment]
@chancancode I agree with this. It's possible that we'll want to use dash-case for *keywords*, but I agree that we can reserve that conversation for later.

**Comment by wycats** [comment]
As a side note: we could consider the new vscode deprecation feature to mark features that we want to discourage. It has pretty nice UI.

**Comment by bertdeblock** [comment]
There is now [an RFC](https://github.com/emberjs/rfcs/pull/689) for deprecating `hasBlock` and `hasBlockParams`.

**Comment by mixonic** [comment]
Closing as I consider this resolved in https://github.com/emberjs/rfcs/pull/689!
