### ISSUE TITLE
[QUESTION]: how do I comment on an RFC?

### ISSUE THREAD

**Issue by williamsbdev** [emberjs/rfcs#49]
I saw that @ef4 had forked the rfcs repo and has one about routable components. I would like to comment and was wondering where I go to do that?

Thanks!

**Comment by ef4** [comment]
Each proposed RFC has a pull request, which is the best place to comment.

https://github.com/emberjs/rfcs/pull/38

**Comment by williamsbdev** [comment]
Thank you! I was looking for issues.
