### ISSUE TITLE
Deprecate `disconnectOutlet`

### ISSUE THREAD

**Issue by chadhietala** [emberjs/rfcs#490]
[disconnectOutlet](https://api.emberjs.com/ember/3.10/classes/Route/methods/disconnectOutlet?anchor=disconnectOutlet) should have been [removed in 2.0](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/routing/lib/system/route.ts#L1704-L1736), however it is still here. #418 should have addressed this as this is simply the destruction side of the route render APIS.

**Comment by rwjblue** [comment]
Lets do it...

**Comment by rwjblue** [comment]
We briefly discussed this at the most recent core team call, and think that this API absolutely should have been included in #418. The general consensus is that this can be a small RFC that is _effectively_ an addendum to #418.

**Comment by chadhietala** [comment]
Closing as I wrote the rfc. #491
