### ISSUE TITLE
Use npx in documentation

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#493]
We currently recommend installing `ember-cli` globally in our documentation, and then using that to run the initial app and addon generation commands.
Now that suppot for Node v6 was dropped, I believe the install for all supported versions come with `npx` out of the box.

**Comment by kellyselden** [comment]
If you did that, wouldn't all commands like build and serve need npx too?

**Comment by rwjblue** [comment]
Using `npx` (I think) means `--yarn` doesn’t work at the moment, but assuming we can fix that it seems good to me. 

RE: serve, we should suggest `npm start` or `yarn start` (which is much better for teams anyways)...

**Comment by jrjohnson** [comment]
I was under the impression from discord discussion around #448 that while `yarn` is OK to use `npm` is the happy path. Given that I don't think `--yarn` support block this move.

**Comment by Turbo87** [comment]
I agree with Kelly. you would need to use npx for all ember commands then which does not seem very ergonomic to me.

**Comment by chriskrycho** [comment]
@jrjohnson it's not that yarn is *okay* to use but npm is the *happy* path; it's that npm is the *default* but—and this  is the important bit—***both are supported by Ember CLI***.

**Comment by NullVoxPopuli** [comment]
did we do this? I think last I saw the docs use npx?

**Comment by locks** [comment]
Superceded by https://github.com/emberjs/rfcs/issues/827.
