### ISSUE TITLE
Change test directories

### ISSUE THREAD

**Issue by mehulkar** [emberjs/rfcs#515]
Change test directories, blueprints, generators

- tests/acceptance -> tests/application
- tests/integration > tests/rendering
- tests/unit/utils -> tests/unit
- tests/unit/controllers -> tests/container/controllers
- tests/unit/routes -> tests/container/routes
- tests/unit/services -> tests/container/services

To match the names given here: https://guides.emberjs.com/release/testing/

**Comment by rwjblue** [comment]
Generally seems good to me.

**Comment by josemarluedke** [comment]
This seems like a natural change. 👍 

For components using [Component Templates Co-location](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html), it would be nice to have tests co-located as well but definably would require an RFC. This was one of the nice things I was hoping to get with MU.

**Comment by buschtoens** [comment]
> For components using [Component Templates Co-location](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html), it would be nice to have tests co-located

Why stop there?

I think that co-locating tests for most files makes a lot of sense, e.g.:

```
some-app
├── README.md
├── app
│   ├── app.js
│   ├── application
│   │   ├── controller.js
│   │   ├── controller.test.js
│   │   ├── route.js
│   │   ├── route.test.js
│   │   └── template.hbs
│   ├── components
│   │   ├── another-component.css
│   │   ├── another-component.hbs
│   │   ├── another-component.js
│   │   ├── another-component.test.js
│   │   ├── pod-style
│   │   │   ├── index.css
│   │   │   ├── index.hbs
│   │   │   ├── index.js
│   │   │   └── test.js
│   │   ├── some-component.css
│   │   ├── some-component.hbs
│   │   ├── some-component.js
│   │   └── some-component.test.js
│   ├── helpers
│   │   ├── some-helper.js
│   │   └── some-helper.test.js
│   ├── index.html
│   ├── resolver.js
│   ├── router.js
│   ├── services
│   │   ├── some-service.js
│   │   └── some-service.test.js
│   ├── some-route
│   │   ├── controller.js
│   │   ├── controller.test.js
│   │   ├── route.js
│   │   ├── route.test.js
│   │   └── template.hbs
│   ├── styles
│   │   └── app.css
│   └── utils
│       ├── some-util.js
│       └── some-util.test.js
├── config
│   ├── environment.js
│   ├── optional-features.json
│   └── targets.js
├── ember-cli-build.js
├── package.json
├── testem.js
├── tests
│   ├── another-acceptance.test.js
│   ├── index.html
│   ├── some-acceptance.test.js
│   └── test-helper.js
└── yarn.lock
```

**Comment by mehulkar** [comment]
I'm usually not in favor of colocating tests and it would definitely be out of scope for this particular RFC if I was going to write it

**Comment by NullVoxPopuli** [comment]
I think colocation of unit and integration tests would be super valuable. But def out of scope here

**Comment by mehulkar** [comment]
Opened #575 for this.
