### ISSUE TITLE
Hide the numbering in the md book output

### ISSUE THREAD

**Issue by chancancode** [emberjs/rfcs#524]
See https://emberjs.github.io/rfcs/

We want to change this:

> 1. 0001-transform-attribute-meta-parameter
> 2. 0003-block-params
> 3. 0003-cli-ember-doctor
> 4. 0010-engines
> 5. 0011-improved-cp-syntax
> 6. 0012-help-json-output
> 7. 0015-the-road-to-ember-2-0
> 8. 0020-sri-default
> 9. ...

...into this...

> 0001-transform-attribute-meta-parameter
> 0003-block-params
> 0003-cli-ember-doctor
> 0010-engines
> 0011-improved-cp-syntax
> 0012-help-json-output
> 0015-the-road-to-ember-2-0
> 0020-sri-default
> ...

...or ideally, even this...

> #0001. Pass through attribute meta data to related Transform
> #0003 Block Params
> #0003 `ember doctor`
> #0010 Engines
> ...

We should be able to do the middle thing quickly with CSS, but maybe this is something we should PR to upstream (mdbook).

**Comment by makepanic** [comment]
the second option already works when configuring mdbook with:
```
[output.html]
no-section-label = true
```
see https://rust-lang-nursery.github.io/mdBook/format/config.html#html-renderer-options

It seems like that option isn't supported in `0.0.26`. I've installed the latest one and the output is as expected:

![20190806-190813](https://user-images.githubusercontent.com/1205444/62563004-6027ef80-b882-11e9-9983-08e7a549666f.png)

**Comment by chancancode** [comment]
@makepanic yes please 🙏

**Comment by makepanic** [comment]
created https://github.com/emberjs/rfcs/pull/526 to fix this issue
