### ISSUE TITLE
There are two RFC 0003

### ISSUE THREAD

**Issue by chancancode** [emberjs/rfcs#525]
🤔

**Comment by rwjblue** [comment]
This is due to the merging of ember-cli/rfcs into this repo. Not much to be done about the number mismatch other than perhaps prefixing the ember-cli ones in some special way.

**Comment by chancancode** [comment]
I see 🤔

**Comment by kategengler** [comment]
The cli ones have `cli` after the number. I did that rather than a prefix so they would be actually interleaved, rather than leaving the old CLI ones in a separate section.
