### ISSUE TITLE
API to properly dispose objects

### ISSUE THREAD

**Issue by chancancode** [emberjs/rfcs#545]
`@ember/object` should provide the following APIs:

```ts
function isDestroying(obj: object): boolean; // same as isDestroying on Ember.Object
function isDestroyed(obj: object): boolean; // same as isDestroyed on Ember.Object
function onBeforeDestroy<T extends object>(obj: T, callback: (obj: T) => void); // same as willDestroy() on Ember.Object
function destroy(obj: object): void; // same as destroy() on Ember.Object
```

This is required for objects that doesn't inherit from Ember.Object (e.g. Glimmer Components, other native classes) to participate in the destruction protocol (dispose of the "meta", etc).

**Comment by chancancode** [comment]
This is required for objects that doesn't inherit from `Ember.Object` (e.g. Glimmer Components, other native classes) to participate in the destruction protocol (dispose of the "meta", etc)

**Comment by NullVoxPopuli** [comment]
Just there be a TS interface that is like C#'s IDisposable?

**Comment by rwjblue** [comment]
Seems good, both ember-lifeline and ember-concurrency could use (and want) this functionality.

**Comment by chriskrycho** [comment]
@NullVoxPopuli the point here (if I'm reading @chancancode's suggestion correctly) is that you don't have to require the object itself to implement all of that interface. That keeps the API surface of the various classes smaller.

**Comment by chancancode** [comment]
Right, or rather, we would provided functions that could be used on any objects, rather than making the objects implement anything. Think Ember.get() vs EmberObject.prototype.get().

**Comment by rwjblue** [comment]
Ya, exactly. This is roughly akin to the [registerDisposable](https://ember-lifeline.github.io/ember-lifeline/docs/register-disposable) in ember-lifeline (and Ember would implement the `runDisposable` concept.

**Comment by rwjblue** [comment]
See an earlier proposal of this here https://github.com/emberjs/ember.js/pull/14602.

**Comment by sandstrom** [comment]
Can we close this?

https://github.com/emberjs/rfcs/pull/580

**Comment by NullVoxPopuli** [comment]
@locks, I think we can close this issue, because `@ember/destroyable` has landed
