### ISSUE TITLE
Allow writing initializer code in app.js

### ISSUE THREAD

**Issue by mehulkar** [emberjs/rfcs#552]
Initializers are simply functions that run during application boot (and similarly instance initializers during ApplicationInstance boot). A hook in App.extend() in app.js would be a better starting point for beginners rather than a new file and folder structure. 

We can enable this by

- exposing the hook
- replacing the place initializers are run with running the hook
- changing the blueprint to run loaded initializers automatically

**Comment by rwjblue** [comment]
FWIW, it is already possible to do this. I think you can call `App.initializer` and `App.instanceInitializer` directly for each.

**Comment by mehulkar** [comment]
I specifically want to change the paradigm and expose a bridge that makes it backwards compatible. The initializer pattern is brought over from Rails, pretty sure, and I don’t think it meshes well in JS land anymore. (Not sure it’s a great pattern for Rails either, tbh).

IMO, there’s no need to have a strict format , export pattern, and directory location for stateless functions, and we are losing out on a teaching moment about Applications vs ApplicationInstances by organizing the code this way.

**Comment by mehulkar** [comment]
Opened #573 for this.
