### ISSUE TITLE
Deprecated unquoted, non-curlies arguments to components

### ISSUE THREAD

**Issue by jenweber** [emberjs/rfcs#564]
This is linted against, but should be disallowed:

```handlebars
<MyComponent @isOpen=true  @count=45 />
```

**Comment by ef4** [comment]
This is probably not a priority, because:

 - we have a strong analogy here with HTML and HTML allows this kind of string passing. It's bad style, but that is what the existing lint rule is covering.
 - Glint gives people another way to avoid this class of bug.

**Comment by jenweber** [comment]
I’ve entirely lost context on what this issue was sparked by. I’m guessing it was a framework team meeting discussion, given the timing. I’ll close it.
