### ISSUE TITLE
Feature Request: new template behavior: switch statements

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#584]
Possible usage:
```hbs
{{#case this.property}}
  {{when "foo"}}  
    No fall-through, because having a {{break}} helper would be weird, imo.
  {{when "bar"}}

  {{when "baz"}}
    boop
{{/case}}
```

this could probably be implemented as an addon, actually, so I don't know how valuable this would be: 

```hbs
{{#switch this.property as |s|}}
  {{#s.when "foo"}}  

  {{/s.when}}

  {{#s.when "bar"}}

  {{/s.when}}
{{/switch}}
```
but then, as @miguelcobain mentioned, it'd be possible to render outside of the `when` blocks, which we wouldn't want.

**Comment by nickschot** [comment]
Wouldn't it make more sense to call it "case" instead of "when" to be consistent with the language?

**Comment by NullVoxPopuli** [comment]
what language? :)

**Comment by nickschot** [comment]
Javascript (and most other programming languages?)

**Comment by miguelcobain** [comment]
This syntax allows rendering things inside the switch but outside the when.
This alternative, something that resembles `{{#if}} {{else}} {{/if}}` wouldn't have that "problem":

```hbs
{{#switch this.property}}

{{case "foo"}}

{{case "bar"}}

{{else}}
  {{!-- a catch all case? --}}
{{/switch}}
```

**Comment by NullVoxPopuli** [comment]
https://www.rubyguides.com/2015/10/ruby-case/
idk
```ruby
    case capacity
    when 0
      "You ran out of gas."
    when 1..20
      "The tank is almost empty. Quickly, find a gas station!"
    when 21..70
      "You should be ok for now."
    when 71..100
      "The tank is almost full."
    else
      "Error: capacity has an invalid value (#{capacity})"
    end
```

**Comment by webark** [comment]
is this the point we start having the jsx conversation? 🤪😇🤓

**Comment by NullVoxPopuli** [comment]
in JSX, it's super easy to have unmaintainable code.

restrictions are beautiful :heart:  :sparkles:  :tada:

**Comment by miguelcobain** [comment]
With the possibility of truth helpers landing in core, I'm not sure if it's worth a switch statement:

```hbs
{{#if (eq this.property "foo")}}

{{else if (eq this.property "bar")}}

{{else}}

{{/if}}
```

Sure, a little bit more verbose and maybe more error prone because of the `this.property` repetition, but still not awful.

**Comment by kpfefferle** [comment]
Considering that Ember is a _JavaScript_ framework, I would think we might favor the JS terminology of `switch` with `case` statements inside: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

Note that `switch` [was suggested as a built-in helper for Handlebars at one point](https://github.com/wycats/handlebars.js/issues/927) (and then rejected as not-lightweight-enough).

 I'd really like to see an addon that adds this as a Handlebars helper (the above Handlebars issue has some examples), but I'm not convinced it should be part of the core framework. I would definitely use it in some projects (I found the above link when looking for a `switch` helper just this week).

**Comment by NullVoxPopuli** [comment]
we could do an addon that does a build time transform that converts switch to ifs. I think that'd be neat.
