### ISSUE TITLE
Deprecate whitespace control in Ember templates using a tilde

### ISSUE THREAD

**Issue by jelhan** [emberjs/rfcs#598]
Whitespaces could be stripped from a value in an ember template using a `~`. As far as I'm aware this is not documented at all for Ember templates and I can't remember that it ever was.

The feature exists from the Handlebars roots of Ember. It's documented for Handlebars: https://handlebarsjs.com/guide/expressions.html#whitespace-control

The same could be achieved using a helper. E.g. a `{{trim}}` helper could take a value as a positional param, convert it to a string and trim whitespaces at start and end of it. It could support to named arguments `start` and `end` that allows the user to disable triming of whitespaces at start or end of the string.

Such a helper would allow to replace existing whitespace control using tilde:

```hbs
{{~foo~}} -> {{trim foo}}
{{~foo}} -> {{trim foo end=false}}
{{foo~}} -> {{trim foo start=false}}
```

It would reduce learning curve as it reduces the complexity of template syntax. It may even reduce complexity of Glimmer VM implementation. But I'm not sure at which level the current whitespace control is implemented.

It should make tooling simpler. Actually I got motivated to do this proposal cause the whitespace control is one of the features not yet supported by Prettier for Ember templates. (Update: I just saw that support has landed 10 days ago in https://github.com/prettier/prettier/pull/7575).

We should be able to provide a Codemod to migrate existing code.

As the feature is not documented at all I think it's replacement helper should be provided as an addon. The addon should not be part of the default blueprint for new Ember apps.

**Comment by buschtoens** [comment]
As far as I know `~` actually trims the whitespace preceeding / following the expression and not the the whitespace of the value of the expression itself.

Example:

```hbs
{{! foo = "foo" }}
<span>
  {{this.foo}}
</span>
```

```html
<span>
  foo
</span>
```


```hbs
{{! foo = "foo" }}
<span>
  {{~this.foo}}
</span>
```

```html
<span>foo
</span>
```


```hbs
{{! foo = "foo" }}
<span>
  {{this.foo~}}
</span>
```

```html
<span>
  foo</span>
```


```hbs
{{! foo = "foo" }}
<span>
  {{~this.foo~}}
</span>
```

```html
<span>foo</span>
```

```hbs
{{! foo = "foo" }}
<span>
  {{~this.foo~}}
</span>
```

```html
<span> foo </span>
```

**Comment by Turbo87** [comment]
AFAIK Intercom is using the tilde heavily to keep their template size down, so deprecating it without a replacement seems like a bad idea 😅

**Comment by jelhan** [comment]
Sorry cause I confused what that tilde does. Wasn't aware that it strips the whitespaces _before_ or _after_ the handlebars expression. Let me close the proposal. Guess it's more about adding missing documentation for that feature.

**Comment by jfrux** [comment]
I know this is lame to ask this here, but how do you get template-lint / prettier from recommending you remove the tilde?  Not finding it in ember template lint or anything.
