### ISSUE TITLE
Remove RSVP?

### ISSUE THREAD

**Issue by mehulkar** [emberjs/rfcs#606]
Is the RSVP library required anymore or can it be dropped in favor of native promises? 

The RFC would be to deprecate it from [the public API][1], but the *harder* problem may be to remove its usage from ember core. I don't [see it as a direct dependency of ember-source][2], so I'm a little unsure what nested dependency makes it available in the first place

According to [bundlephobia][3], it would be a nice chunk of bytes back

[1]: https://api.emberjs.com/ember/release/modules/rsvp
[2]: https://github.com/ember-cli/ember-cli/blob/v3.16.0/blueprints/app/files/package.json
[3]: https://bundlephobia.com/result?p=rsvp@4.8.5

**Comment by locks** [comment]
I want to point out that Ember still supports IE11 so we would at least need a polyfill alternative.

**Comment by chriskrycho** [comment]
Actually, if we deprecated it and turned it into an optional feature, we could in principle let people start opting out as they're able, with a plan to drop when Ember 4.0 happens.

One important note is that RSVP deeply integrated with the the router, the run loop, and (not least importantly!) the *test* suite—particularly with the test waiters system.

**Comment by mehulkar** [comment]
This is a dupe of #539
