### ISSUE TITLE
[Ember CLI] Deprecate bower APIs

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#610]
More context at https://github.com/ember-cli/ember-cli/issues/9110.

Ember CLI still contains internal APIs to support bower. These should be deprecated for later removal.

**Comment by Gaurav0** [comment]
> Ember CLI still contains internal APIs to support bower. These should be deprecated for later removal.

I believe there are several public apis supporting bower as well.

**Comment by rwjblue** [comment]
> I believe there are several public apis supporting bower as well.

Ya, at least `Blueprint.prototype.addBowerPackageToProject` ([see here](https://github.com/ember-cli/ember-cli/blob/6ffd7e56bd3487ff1e63ea9e1e7628199432ac04/lib/models/blueprint.js#L1019)).

**Comment by locks** [comment]
Assigned to @bertdeblock.
