### ISSUE TITLE
lazy Route-Based bundling

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#611]
The Goal:

> Provide a way to dramatically improve (re)build times during development while also increasing the maintainability of large apps based on common mitigations seen across the ecosystem

This idea will require embroider, and for implementation will require embroider become the default bundler for ember.

Prereqs:
 - embroider in use
 - app is statically analyzeable enough to where embroider is capable of automatically split bundles on route boundaries

But the gist is:
 - lazy route-based bundling is for development only
 - when starting `ember serve`, ember-cli starts a server that can communicate with embroider, but does not build the app
 - when ember-cli receives a request to any route, that route is passed to embroider, and embroider builds the bundle for that route
 - when the bundle for a route is being built, we could display some dev-time only UI that shows what is happening in the browser - or loading.hbs / loading routes could be used if those are loaded (after initial load -- or maybe these templates / routes are included in the base bundle)
 
Why:
 - very large apps have build and rebuild problems - it takes too long to (re)build
 - engines have many caveats and introduce complexity for app devs
 - the other common approach, splitting your app into multiple separate apps has a few disadvantages:
   - full page refresh between apps (white screen)
   - managing code, upgrades, etc across multiple apps is difficult (esp across multiple repos, a mono repo may help a bit)
   - for multi-route (multi-app) interactions you need to boot multiple ember-servers, which starts to constrain your computing resources

Lazy route-based bundling allows you to have a single `ember serve` without eating the cost of having a giant app. 

Note: this in no way is suggesting anything change for building the app(s) for deployment.

When wouldn't this make sense?
 - app is small? (# routes less than 50, perhaps)
 - rebuild time is already under 30s (this may seems slow as a baseline, but this idea of lazy route-based bundling is intended for _very_ large apps (hundreds of routes)

**Comment by villander** [comment]
> engines have many caveats and introduce complexity for app devs

@NullVoxPopuli the build/rebuild with engines has the same problems. It should be fixed in some engine level as well.

**Comment by sukima** [comment]
I’m curious but what is the blocker to the build chain? I mean it already knows what files have changed. It only has to transpile (build) a small number of source files.

What I’m saying is if we split the development payload into individual files instead of one big vender/app file. Would that satisfy the problem?

If so we could ship the split payloads over HTTP/2 and or manage a web socket to send changed files.

More specific how does the current routing system play into the performance of the build?

**Comment by NullVoxPopuli** [comment]
Partial transpiling today only works after the whole build has finished.
The main issue is that because our apps are kinda dynamically resolved, there isn't a way to know how much of an app's code (and parts of addons) are need for any particular route. This is what embroider's strict mode provides.

**Comment by mehulkar** [comment]
The Snowpack/Vite model feels really right, tbh. Why bundle at all in development (coming at this from pie-in-the-sky goggles)
