### ISSUE TITLE
Support importing JSON

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#647]
today, if you have

```json5
// some-json.json
{
  "json": "json"
}
```

you can't, in any JS file do:
```js
import json from 'some-json.json';
```

**Comment by rwjblue** [comment]
Hmm, why is this an RFC issue? Seems like this is a thing that ember-auto-import / embroider _could_ enable (though I'd have to re-read the Addon V2 RFC to see if it is implicitly included there as part of "following Node module resolution").

**Comment by NullVoxPopuli** [comment]
> why is this an RFC issue?

Feature request for a default for the ecosystem?

**Comment by rwjblue** [comment]
My point is that I think we already agreed that we should do it (by saying we follow the node module resolution algorithm). 

See https://github.com/emberjs/rfcs/blob/master/text/0507-embroider-v2-package-format.md#play-nice-with-npm-conventions which links to https://nodejs.org/api/all.html#modules_all_together, which **explicitly** lists support for resolving `.json` files.

**Comment by NullVoxPopuli** [comment]
Excellent!
