### ISSUE TITLE
[deprecate] fallback lookup paths in ember-resolver

### ISSUE THREAD

**Issue by gabrielcsapo** [emberjs/rfcs#661]
Currently we have multiple fallback lookup paths in ember-resolver.  As we continue to migrate towards a more strict future where imports are verified at build time (https://github.com/emberjs/rfcs/pull/454) it would be forward looking to remove non-strict lookups from ember-resolver to make codemods to migrate to; 
- Strict Mode (https://github.com/emberjs/rfcs/pull/496)
- the v2 addon format (https://github.com/emberjs/rfcs/pull/507)
- the slimming down the ember-cli build pipeline (https://github.com/emberjs/rfcs/pull/578)
- strict service lookups (https://github.com/emberjs/rfcs/pull/585) 

It would benefit the ecosystem to remove fallback logic that enables many-to-one lookups in favor of a one-to-one mechanism.

The knock on effects of this would be having a supported solution to solve the following;
- Where does Pod resolution go and is supported?

An example of what this resolver would look like after removing all fallback lookup paths would be https://github.com/stefanpenner/ember-strict-resolver.

**Comment by rwjblue** [comment]
FWIW, I'm definitely in favor of a path forward here.

**Comment by gabrielcsapo** [comment]
@rwjblue will work on an RFC to get a path forward planned out.

**Comment by wagenet** [comment]
Looks like we have an RFC so I'll close this ticket.
