### ISSUE TITLE
Deprecate Ember AutoLocation

### ISSUE THREAD

**Issue by sandstrom** [emberjs/rfcs#693]
Seems like PushState is supported in most browsers today:
https://caniuse.com/?search=pushState

So basically everyone using a browser supported by Ember will get `HistoryLocation` when they select `AutoLocation`.

The current detection code is this:

```ts
export function supportsHistory(userAgent: string, history: History): boolean {
  // Boosted from Modernizr: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/history.js
  // The stock browser on Android 2.2 & 2.3, and 4.0.x returns positive on history support
  // Unfortunately support is really buggy and there is no clean way to detect
  // these bugs, so we fall back to a user agent sniff :(

  // We only want Android 2 and 4.0, stock browser, and not Chrome which identifies
  // itself as 'Mobile Safari' as well, nor Windows Phone.
  if (
    (userAgent.indexOf('Android 2.') !== -1 || userAgent.indexOf('Android 4.0') !== -1) &&
    userAgent.indexOf('Mobile Safari') !== -1 &&
    userAgent.indexOf('Chrome') === -1 &&
    userAgent.indexOf('Windows Phone') === -1
  ) {
    return false;
  }

  return Boolean(history && 'pushState' in history);
}

```

Would it make sense to deprecate `AutoLocation` and use `HistoryLocation` as the new default? 

https://api.emberjs.com/ember/release/classes/AutoLocation

We'd still want to retain `HashLocation` of course, so it can still be chosen.

In case anyone still need to switch between the two depending on availability they could import `modernizer` and check manually, before making their choice.

Let me know what you think! Good idea? Bad?

***

Somewhat related we could also remove `Ember.Location.registerImplementation` (been deprecated for several years now).

https://github.com/emberjs/ember.js/commit/087e21888a449a8086c69dbea9709677c798b0fa

**Comment by rwjblue** [comment]
Yes. We should deprecate AutoLocation (via an RFC), the original reason for it was the browser support issue but that is no longer a concern as of 3.0.0.

**Comment by sandstrom** [comment]
I've added an RFC here:
https://github.com/emberjs/rfcs/pull/711

Let me know what you think!
