### ISSUE TITLE
Deprecate PromiseProxyMixin, PromiseArray, and PromiseObject

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/rfcs#721]
This is blocked on dropping 🔥 DIAF IE11 🔥 support with Ember 4, but once we do, we can begin the deprecation staging process for replacing `PromiseProxyMixin`, `PromiseArray`, and `PromiseObject`. This would have a couple nice knock-on effects:

1. It would remove APIs long known to weird behavior: the way that `PromiseProxyMixin` and things derived from it try to make the Promise "invisible".
2. It would remove one of the major blockers for removing `Mixin` in general, as these are some of the key (public API-visible) uses of Mixins in the framework.

Notably, each of these can be straightforwardly (though not necessarily transparently!) replaced by Octane idioms. The `PromiseArray` and `PromiseObject` types can likely be reimplemented in terms of native `Proxy` and *also* deprecated in favor of less confusing idioms, but doing it that way would allow us to drop `PromiseProxyMixin` first and then drop those two types later. That will also likely be necessary for making the transition work for Ember Data users.

**Comment by runspired** [comment]
fwiw PromiseArray and PromiseObject do not come from ember but rather from ember-data and we already deprecated using them directly.

**Comment by wagenet** [comment]
See #832
