### ISSUE TITLE
Decoration

### ISSUE THREAD

**Issue by sandstrom** [emberjs/rfcs#74]
Ember has used decorators for a long time. Both in the form of `ObjectController`, used either along with the `itemController` property in `{{#each}}` helpers in templates or on `ArrayController`, and with the public `ObjectProxy` class.

I think the move from controllers to components is a good one! But I also find the decoration pattern useful (it exist in many frameworks, not only Ember) for some things. Maybe not for a simple TODO-app, but certainly for more advanced client applications.

Most of this can be implemented using other primitives, but parts of it would benefit from better framework support.

One is unwrapping of decorators in the action controller, which already exist for `ObjectController`[1].

~~A possible solution is to introduce a lightweight object, `Ember.Decorator` with a duck typing property such as `isDecoratorFactory: true` used to trigger unwrapping in the action helper. Unwrapping would simply be a function called e.g. `unwrap`, and it would be up to the decorator to unwrap itself.~~

If it was possible to 'sub-class' the action helper (basically get a chance to act on action helper invocations) adding decorator-unwrapping would be easy. It would also allow for other things, for example logging of all action calls.

---

[1] https://github.com/emberjs/ember.js/blob/4200641b9142/packages/ember-views/lib/streams/utils.js#L40

**Comment by mmun** [comment]
@sandstrom I'm very much looking forward to removing the linked piece of code. The problem with proxies is that they are a leaky abstract that is very viral. Even our base Stream class has to have special code to work with Proxies: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/streams/stream.js#L180-L202.

I would much prefer experimenting with how we can push decorating into userspace.

**Comment by sandstrom** [comment]
@mmun I understand the concern. If the unwrapping happened in the actions-handling of routes and components instead, is that something you'd prefer? (I think that'll work equally well for all use-cases I can think of)

**Comment by sandstrom** [comment]
friendly ping @mmun :smile:

**Comment by mmun** [comment]
@sandstrom Sorry, I missed this. I think that implicit unwrapping anywhere is the codesmell of a bad pattern. So I'm not a fan.

**Comment by stefanpenner** [comment]
ES6 proxies (once enough platforms support) will be an abstraction that doesn't have the same issues.

The question is, what should exist in the interim? How do we minimize the leaks and confusions of today

**Comment by sandstrom** [comment]
Decoration is useful in various situations, and a common pattern across languages and frameworks. For decoration to work well with actions unwrapping is desired — which is why this is implemented in Ember. 

I understand that you dislike it, but it must not be default. Ember is extensible in many ways, which is great. But this is a place where it's currently hard.

Say, for example, there was a method one could override in routes/components—to act on the action arguments before they were passed on to the action-handler—that would be enough. There wouldn't even be unwrapping in the framework, only some method that made it possible to implement for those who need it.

**Comment by stefanpenner** [comment]
> Decoration is useful in various situations, and a common pattern across languages and frameworks. For decoration to work well with actions unwrapping is desired — which is why this is implemented in Ember.

We don't argue it isn't useful, rather in JS today it some with a hefty abstraction leak cost.

**Comment by mmun** [comment]
I get decorators. I'm fine with explicit unwrapping. I'm not fine with implicit unwrapping. I've been burned too many times, across multiple languages and frameworks.

**Comment by sandstrom** [comment]
> If it was possible to 'sub-class' the action helper (basically get a chance to act on action helper invocations) adding decorator-unwrapping would be easy. It would also allow for other things, for example logging of all action calls.

This should be possible now, with actions being simple functions one can curry or wrap a function to provide the desired unwrapping-functionality.

I'll close this issue.
