### ISSUE TITLE
Feature Request: Make it easier to use Markdown in .hbs file.

### ISSUE THREAD

**Issue by MelSumner** [emberjs/rfcs#765]
It would be a QOL improvement to have .hbs files also support markdown. I don't think I have opinions on how I think this should work, just should be super easy. Maybe a config switch? Markdown blocks? I'm sure there are a ton of paths that would get to this outcome.

**Comment by NullVoxPopuli** [comment]
Like.. glimdown? https://limber.glimdown.com?

**Comment by gossi** [comment]
... or [`ember-cli-markdown-it-templates`](https://github.com/effective-ember/ember-cli-markdown-it-templates)?

**Comment by jherdman** [comment]
We've long used an Ember addon to process markdown in our templates https://github.com/PrecisionNutrition/render-markdown. This has proven an effective strategy for us as we can customize how the markdown is processed for specific business needs.

**Comment by MelSumner** [comment]
@gossi yup https://github.com/effective-ember/ember-cli-markdown-it-templates is really close to what I am thinking. Gave it a try today and was pretty surprised at how close it was to what I imagined. 💯

**Comment by gossi** [comment]
Aww, that's nice to hear. What's missing for you? There are some hidden features =)

**Comment by NullVoxPopuli** [comment]
in most markdown parsers, to escape back to markdown, you need extra line breaks:
```
<MyMarkdownBlock>
  <template>
  
  ## Hello from Markdown
  
  </template>
</MyMarkdownBlock>
```

**Comment by chriskrycho** [comment]
@MelSumner given the variety of options in the community already, do you still want to leave this open? That is, do you see value in trying to make it a first-party/officially-maintained item, rather than something built on top of the core we do support?

**Comment by wagenet** [comment]
I’m going to go ahead and close this. It’s a great idea but it seems to have stalled. If anyone would like to pick it up and get it moving again, please let me know.

**Comment by NullVoxPopuli** [comment]
I wouldn't consider no comments for a few months stalled :p 

But, I would like to see an unplugin plugin that does this transform.

There are some details with how markdown -> glimmer -> markdown interop works with line breaks, that I've been meaning to formalize via commonmark plugin. Time is an issue tho. 

Some readme-driven-development here: https://github.com/NullVoxPopuli/glimdown

**Comment by chriskrycho** [comment]
I will take this as an opportunity to state directly that in my opinion there's no reason this needs to be core functionality. The comparable stuff in other ecosystems is *not*, and the bar for having something be officially maintained and supported is *and should be* higher – we have limited resources, and zero people working full time on these things, so while I think it would be great if this existed, I also don't think it should be part of the core framework.

That said, if in the process of working on integrations with things like markdown-it and other JS Markdown tools, we find a limitation in the framework which makes the interop fundamentally broken or needlessly difficult, then addressing *that gap* would warrant an RFC.

**Comment by wagenet** [comment]
I’m 100% I’m agreement with @chriskrycho here. I’m going to go ahead and close this. As Chris said, we can definitely work to address any things that make the creation of such an add on difficult.

**Comment by NullVoxPopuli** [comment]
:100: the fact this is all possible in user-land is _quite fun_! :partying_face:
