### ISSUE TITLE
Feature Request: provide a new built-in component for automatically selecting the correct H# element.

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#766]
This came up during a conversation with @zoebijl, where, we as developers, do not have a great to both developer increasingly complex/composed component/wrappers while also correctly managing the heading level. I think this should could be done automatically via special component (or built in user-land with maybe a perf-cost), but the gist is that a component should be able to give you the correct h1, h2, h3, or whichever level you need, based on where the component is overall rendered in your document.

In user-space, this would be implemented something like:
```hbs
{{!-- <Heading> implementation --}}
<FindHeadingLevel as |recommendedHeading|>
  {{#let (element recommendedHeading) as |CorrectHeading|}}
    <CorrectHeading>
      {{yield}}
    </CorrectHeading>
  {{/let}}
</FindHeadingLevel>
```
where `FindHeadingLevel` implements logic, maybe via [TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) that follows the same rules for when headings should be incremented that our accessibility testing tools, such as aXe, use. 

This way, when a developer wants to use a h1/h2/h3, etc, we can lint against that, and recommend (or auto-fix to) the `<Heading />` component.

```hbs
<Heading>My Title</Heading> <!-- h1 -->

<section>
  <Heading>My Section</Heading> <!-- h2 -->
  
  ...
</section>
```

The motivation here is that HTML and the general web is hard to get right, and the more we can do _for_ developers, the more accessible our apps will be :D

**Comment by mrloop** [comment]
This reminds me of the document outline algorithm, if natively implemented by browsers we'd get the appropriate heading level depending on how far down a h1 tag was nested in sectioning elements https://www.smashingmagazine.com/2020/01/html5-article-section/#so-what-about-lt-section-gt

**Comment by ZoeBijl** [comment]
The [HTML specification section on headings and sections](https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections) might have helpful information.

Please note that the statement about using only `<h1>`s as being correct is **false**.

**Comment by sandstrom** [comment]
From our perspective, we wouldn't have much use for it (we use mostly DIVs and don't spend any time on writing semantic HTML), and in the cases where I've wanted to write semantic HTML, it hasn't been an issue. Basically, in the realm of all possible things that Ember could work on, or put into core, I don't see this as a priority.

So in my view, this is better suited for an addon. Also typically a good way to test if there is a lot of interest.
