### ISSUE TITLE
Deprecate ajax for fetch

### ISSUE THREAD

**Issue by snewcomer** [emberjs/rfcs#782]
Right now, ember-data's adapters connote the use of jquery/ajax through public-ish methods.  

> See [minimum-adapter-interface](https://github.com/emberjs/data/blob/master/packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts) for the proper public API of ember-data's adapters.  Note there is no mention of `ajax`, but there are many [methods](https://github.com/emberjs/data/blob/e076e0ae71ae6426ca53ad3c5501a0af7ceca883/packages/adapter/addon/rest.ts#L1091-L1126) that users tend to override in their adapters.

With Ember 4.0 dropping jQuery, we should take a hard stance on dropping the use of Ajax in the next major release.  Currently in 4.0, ember-data does suggest the use of [`fetch`](https://github.com/emberjs/data/pull/7792/files#diff-932693a0d32639d2ef4116b0d4060d31d063f287c74b53bd03466b4a2eb9407fR346) in their adapters but can be overridden by setting `useFetch = false`.

In managing our transition to `fetch` based methods, we can do some light maintenance work to expose `fetch` related methods and drop switching between fetch and ajax with `useFetch`.  The goal here would be to help improve user's understanding and use of our adapters. Moreover, this refactor may help us take a very small step to a world where we completely rethink the idea of adapters/serializers.

https://github.com/ember-cli/ember-fetch

**Comment by wagenet** [comment]
Can we just make the RFC for this?

**Comment by runspired** [comment]
@wagenet there is #790
