### ISSUE TITLE
Deprecate `addons.blacklist` and `addons.whitelist` build options

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#792]
[RFC 639](https://emberjs.github.io/rfcs/0639-replace-blacklist-whitelist.html) was merged, [implemented](https://github.com/ember-cli/ember-cli/pull/9595) and released in [Ember CLI v4](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#v400).
Now that we have the corresponding alternatives available, I think we can deprecate these options, as having multiple ways of accomplishing the same thing seems undesirable?

**Comment by sandstrom** [comment]
I think Ember as a community should spend less time being woke, and more time building a great JS framework. Renaming variables because someone, somewhere is offended by them isn’t time well spent.

**Comment by bertdeblock** [comment]
Hi @sandstrom, thank you for your comment. To be honest, I personally have no interest in any discussions related to the old keys, why new keys were introduced, if this is time well spent, etc. Those discussions were already part of the RFC itself. I merely created this issue as a reminder that we should deprecate the old keys in favour of the new ones, so we can complete to transition in v5.

**Comment by bertdeblock** [comment]
Going to close this issue in favour of the open PR.
