### ISSUE TITLE
Make Ember.ObjectProxy and Ember.ArrayProxy Public (not private)

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/rfcs#80]
`Ember.ObjectProxy` and `Ember.ArrayProxy` are great to use in combination with `Ember.PromiseProxyMixin` like Ember Data uses them. However ObjectProxy and ArrayProxy are marked **Private** API.

It would be great for addon developers and app developers alike to be able to use ObjectProxy and ArrayProxy combined with Ember.PromiseProxyMixin to compose attributes of an object that depend on promises e.g. XHR. 

Please make ObjectProxy and ArrayProxy public API. I don't believe this combo is only unique to Ember Data. Anyone writing custom data persistence benefits from the same pattern as Ember Data does. Why does this need to be private API? 

I understand ObjectController and ArrayController are deprecated and extend ObjectProxy and ArrayProxy respectively. I understand the confusion for new developers using those proxied controllers and I understand that Controllers will be replace with Components in 2.0. However I don't see why the ObjectProxy and ArrayProxy need to be private API.

Is there another way to use PromiseProxyMixin aside from combining a proxy object/array?

Below is the use case I have for a data persistence library…

A utility object (RelatedProxyUtil) with a factory creates proxies, to be used in a computed property:

```javascript
/**
  Proxy for the requested relation, resolves w/ content from fulfilled promise
  @method createProxy
  @param {Resource} resource
  @param {Ember.ObjectProxy|Ember.ArrayProxy} proxyFactory
  @return {PromiseProxy} proxy
*/
createProxy: function (resource, proxyFactory) {
  const relation = this.get('relationship');
  const url = this.proxyUrl(resource, relation);
  const service = resource.container.lookup('service:' + pluralize(relation));
  let promise = this.promiseFromCache(resource, relation, service);
  promise = promise || service.findRelated(relation, url);
  let proxy = proxyFactory.extend(Ember.PromiseProxyMixin, {
    'promise': promise, 'type': relation
  });
  proxy = proxy.create();
  proxy.then(
    function (resources) {
      proxy.set('content', resources);
    },
    function (error) {
      console.error(error);
      throw error;
    }
  );
  return proxy;
}
```

A helper that uses the proxy util and returns a computed property:

```javascript
/**
  Helper to setup a has one relationship to another resource
  @method hasOne
  @param {String} relation
*/
export function hasOne(relation) {
  let util = RelatedProxyUtil.create({'relationship': relation});
  let path = ['relationships', relation, 'links', 'related'].join('.');
  return Ember.computed(path, function () {
    return util.createProxy(this, Ember.ObjectProxy);
  }).meta({relation: relation, kind: 'hasOne'});
}
```

**Comment by Gaurav0** [comment]
I would actually like to at least see an addon that restores all the ArrayController / ObjectController / reduceComputed / ObjectProxy / ArrayProxy etc. behavior. This could really help some enterprises with large codebases move to 2.0 at some point in the current century. :)

**Comment by mixonic** [comment]
@Gaurav0 there is an addon for controllers ([ember-legacy-controllers](https://github.com/emberjs/ember-legacy-controllers)) and views ([ember-legacy-views](https://github.com/emberjs/ember-legacy-views)). array/reduce computed are gone, but the macros that represented nearly all of the usage are still present. Just the direct API access to the array/reduce computed classes is gone.

Please keep this issue focused on the original topic, object and array proxies.

**Comment by workmanw** [comment]
:+1: I use both ArrayProxy and ObjectProxy on occasion. I think quite a few people also use [ember-buffered-proxy](https://github.com/yapplabs/ember-buffered-proxy) which relies on them.

**Comment by DingoEatingFuzz** [comment]
We also use ObjectProxy and ArrayProxy with the PromiseProxyMixin in places where ED doesn't make sense.

Our PromiseArray is as simple as
```js
import Ember from 'ember';

export default Ember.ArrayProxy.extend(Ember.PromiseProxyMixin);
```

**Comment by pixelhandler** [comment]
Wait, I see some changes already:

- https://github.com/emberjs/ember.js/commit/84909b21960e8b19a5e3d2d7f74febe227bf83af

So ObjectProxy is already public, nice.

Just need ArrayProxy to be public as well

- https://github.com/emberjs/ember.js/pull/11970

**Comment by mmun** [comment]
One caveat with ObjectProxy is that it is not compatible with removing Ember.get in favor of ES5 getters.

**Comment by mixonic** [comment]
@pixelhandler I've merged https://github.com/emberjs/ember.js/pull/11970, should this be closed then or are there additional parts to discuss?

**Comment by pixelhandler** [comment]
@mixonic awesome thank you sir! all set, closing this up :+1:

**Comment by pixelhandler** [comment]
@mixonic @mmun is that why http://emberjs.com/api/classes/Ember.ObjectProxy.html is *Private* and http://emberjs.com/api/classes/Ember.ArrayProxy.html *Public* (I use these alot with http://emberjs.com/api/classes/Ember.PromiseProxyMixin.html which is also Public)

**Comment by rwjblue** [comment]
@pixelhandler - `Ember.ObjectProxy` is marked as `@public` ([see here](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/object_proxy.js#L71) on master).  The API docs you linked to are for 2.0.1 which are somewhat behind.
