### ISSUE TITLE
Additional helpers?

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#802]
kind of gauging interest here, kinda inspired by this thread: https://twitter.com/x8BitRain/status/1498563445058584576

_and_ with the future of ESM / you only ship what you import (along with the recently merged first-class-component templates RFC),

I think we could add a lot more quality-of-life helpers that don't end up impacting the folks that don't use those helpers.

Like, we could add, maybe for strict-mode only:
 - noop

and not sure what else, because with the default helper manager RFC _nearly_ implemented, we get a bunch more helpers for free, via:

```jsx
let someArray = [[1], [2]]

<template>
  {{Array.prototype.flatten someArray}}
</template>
```

though, not ideal to do it this way.. cause Array.prototype.flatten is _long_

hmmmmmmm

thoughts? ideas?

**Comment by chriskrycho** [comment]
@NullVoxPopuli I think the examples you give here, having #756 plus a fix to make method dispatch work as expected would solve nicely. You can import `noop` (or define it) easily enough, and something like `flat` would "just work" as an instance on the array itself:

```js
let someArray = [[1], [2]];

<template>
  {{(someArray.flat)}}
</template>
```

(In general, my own inclination is to have Ember focus on the things _it specifically_ brings to the table, while letting lodash etc. handle general JS utility behavior.)

**Comment by wagenet** [comment]
I’m closing since there doesn’t seem to be a path forward. However, I will happily reopen if one is proposed!

**Comment by NullVoxPopuli** [comment]
atm, with methods on objects, we get an error: `Uncaught (in promise) TypeError: can't convert undefined to object`

[Repro here](https://limber.glimdown.com/?t=Options%3A%0A%0A%20-%20%60live%60%20-%20_renders%20in%20place_%0A%20-%20%60live%20preview%60%20_renders%20in%20place%2C%20placing%20the%20source%20after%20the%20live%20render_%0A%20-%20%60live%20preview%20below%60%20_renders%20in%20place%2C%20placing%20the%20live%20render%20below%20the%20source_%0A%0A%23%23%20Testing%20Array.prototype.flat%0A%0A%60%60%60gjs%20live%0Aconst%20someArray%20%3D%20%5B%5B1%5D%2C%20%5B2%5D%2C%20%5B3%5D%2C%204%5D%3B%0A%0A%3Ctemplate%3E%0A%20%20%7B%7B%20(someArray.flat)%20%7D%7D%0A%3C%2Ftemplate%3E%0A%60%60%60%0A)

**Comment by chriskrycho** [comment]
Yep, what we need is to see if we can fix method handling so it works the way people expect it to. Namely: if you actually *have* a reference to an object and call a method on it, that should work, just like in JS. The spec group has talked about this a few times and come up with some possibly workable ideas but we need someone with the relevant knowledge to champion and drive forward that work.

**Comment by chriskrycho** [comment]
(To clarify, I don’t mean “someone from the community needs to volunteer,” though if someone does that’s awesome and we would try to help get them leveled up. But even on Framework the list of folks with expertise in the Glimmer syntax and semantics needed to drive this and time to work on it specifically is short at present.
