### ISSUE TITLE
Remove `ember-export-application-global` addon from `app` blueprint

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#807]
- Do people still actually use this?
- Does it cover something that e.g. `ember-inspector` doesn't provide?

**Comment by rwjblue** [comment]
I personally would love to remove it, I doubt folks use it (because we don't really have any guides/docs on how to use it)...

**Comment by sandstrom** [comment]
I'm in favor of removing. 

We do something like `window.appInstance = appInstance` from an initializer, to make debugging easier.

My point is that even with this removed, it's still easy to make it globally available when needed. No real need for an add on.

**Comment by bertdeblock** [comment]
Closing since https://github.com/ember-cli/ember-cli/pull/9825#event-6434995558 is merged!
