### ISSUE TITLE
Provided attributes are not installed on a component's attrs hash as of 1.10, in contradiction to "The Road to Ember 2.0 RFC"

### ISSUE THREAD

**Issue by maxkwallace** [emberjs/rfcs#81]
The text of [The Road to Ember 2.0 RFC](https://github.com/emberjs/rfcs/pull/15) states:

> In Ember 1.10, we will begin installing provided attributes in the component's attrs hash. If a provided attribute is accessed directly on the component, a deprecation warning will be issued.
> 
> In applications, you should update your component JavaScript and templates to access provided attributes via the component's attrs property.

As far as I can tell, this is incorrect-- but please correct me if I'm wrong. I tested the behavior with Ember 1.12.0 and 1.13.3, and found that:
- `this.attrs` is undefined in Components as of 1.12.0
- Attributes are available on `this.attrs` as specified when using 1.13.3

So it looks like attributes did not start being installed on the component attrs hash until 1.13... if this is the case, the RFC should be updated. Thanks!

**Comment by Panman8201** [comment]
I'm not really sure this could be back-ported... I think the ship has sailed on this. There were other things with the Ember 2.0 RFC that haven't come to fruition yet either.

**Comment by maxkwallace** [comment]
Sure. But I wasn't asking for a back-port-- only an update to the documentation.

The issue is not that the functionality is missing prior to 1.13, but that the RFC is incorrect about when the functionality was added. Either way, this is a pretty minor issue, so I'm fine with closing it. Just thought I'd try to save someone else some time... I went looking for `this.attrs` using 1.12 and kept wondering if I was doing something wrong.

**Comment by locks** [comment]
Reading this issue was a trip down memory lane!
@maxkwallace while RFCs are not normative, I still understand your pain and I believe we've learned a couple of things about deadlines and releases ;) With the revert of angle bracket components, most of the other stated intentions are still to be delivered too.
I'll close this issue as a lot has happened since.
