### ISSUE TITLE
Replace `babel-eslint` with `@babel/eslint-parser` in blueprints

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#817]
There are two PRs over in `ember-cli`, to try and make this transition happen:
- https://github.com/ember-cli/ember-cli/pull/9556
- https://github.com/ember-cli/ember-cli/pull/9669

The conclusion seemed to be that [this would require an RFC](https://github.com/ember-cli/ember-cli/pull/9556#issuecomment-854046634).

Opening this issue as a reminder, but mainly to gather some feedback on the matter,
and to see if anyone is up for writing this one.

I'm also interested in (co-)writing this RFC, but it's not 100% clear to me what exactly needs to happen.

**Comment by SergeAstapov** [comment]
The solution proposed in https://github.com/ember-cli/ember-cli/pull/9556 did seem require an RFC as it was introducing `babel.config.js` file.

On the other hand, solution proposed in https://github.com/ember-cli/ember-cli/pull/9669 *does not* require `babel.config.js` file as it suggests `.eslintrc.js` would have following part (file trimmed for clarity):

```js
module.exports = {
  root: true,
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
    requireConfigFile: false,
    babelOptions: {
      plugins: [
        ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],
      ],
    },
  },
};
```

I wonder if we go this route, would we really need an RFC as it seem does not change anything as opposed to https://github.com/ember-cli/ember-cli/pull/9556 which has [respective comment from @rwjblue](https://github.com/ember-cli/ember-cli/pull/9556#issuecomment-854046634).

**Comment by wagenet** [comment]
It looks like there may be progress on https://github.com/ember-cli/ember-cli/pull/9669. I'll leave this open for now to see where that goes.
