### ISSUE TITLE
Deprecate support for `ember-cli-qunit` and `ember-cli-mocha` when generating test blueprints

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#824]
[ember-cli-qunit](https://github.com/ember-cli/ember-cli-qunit) was deprecated in favour of [ember-qunit](https://github.com/emberjs/ember-qunit).
[ember-cli-mocha](https://github.com/ember-cli/ember-cli-mocha) was deprecated in favour of [ember-mocha](https://github.com/emberjs/ember-mocha).

I think this would greatly reduce the amount of test blueprint files included in `ember-source` and `ember-data`.

**Comment by wagenet** [comment]
@bertdeblock sounds good to me. Do you need help getting an RFC written?

**Comment by bertdeblock** [comment]
@wagenet Atm, I don't think so. Just need to find some time to get to it.

**Comment by bertdeblock** [comment]
Closing in favor of the actual RFC: https://github.com/emberjs/rfcs/pull/847.
