### ISSUE TITLE
Deprecate support for Travis CI

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#855]
Wondering if Travis CI is still (widely) used across the ecosystem and if we should drop support for it.
I can't find many hits on [emberobserver.com](https://emberobserver.com/).

Thoughts?

**Comment by acorncom** [comment]
I think dropping support for it would be wise, believe Heroku getting hacked had to do with security issues at Travis 3+ months ago

**Comment by chriskrycho** [comment]
Yeah, agreed. Sad story but at this point the rest of it only gets sadder as far as I can see.

**Comment by wagenet** [comment]
@bertdeblock do you want to write this RFC?

**Comment by bertdeblock** [comment]
@wagenet This was briefly discussed during one of the previous CLI meetings and the outcome was that it's not a priority and that some people might still be using Travis CI happily (only speculation of course). But I might end up writing a small RFC nonetheless, I may have some time in the coming weeks.

**Comment by bertdeblock** [comment]
Closing in favor of https://github.com/emberjs/rfcs/pull/918.
