### ISSUE TITLE
Deprecate `ember-export-application-global` addon?

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#882]
We don't maintain this addon anymore and we also recently [removed it from the `app` blueprint](https://github.com/ember-cli/ember-cli/pull/9825).
What it does (setting the app instance on `window`) can also easily be done on a project level if needed.
Seems best to me, to officially deprecate it.

Related RFC issue: https://github.com/emberjs/rfcs/issues/807.

**Comment by bertdeblock** [comment]
Do we need an actual RFC for something like this? The addon hasn't had a release in 6 years so I would say it's already "deprecated"? We could just add a note in the README and archive the repo?

**Comment by wagenet** [comment]
For this one I'd just go ahead, deprecate the repo directly without an RFC.

**Comment by bertdeblock** [comment]
@wagenet https://github.com/ember-cli/ember-export-application-global/pull/188, does something like this seem okay to you?

**Comment by wagenet** [comment]
That PR looks good to me, let's close this and continue any necessary discussion over there.
