### ISSUE TITLE
Allow components to define helpers

### ISSUE THREAD

**Issue by mfpiccolo** [emberjs/rfcs#89]
I might be missing something but this seems like it would be useful.

some-component.js

``` javascript
import Ember from 'ember';

var SomeComponent = Ember.Component.extend({
  helpers: {
    atify: function (some_string) {
      return some_string.replace('a', '@');
    }
  }
});

export default SomeComponent;
```

some-component.hbs

``` html
<div>
  {{ atify 'Crazy' }}
</div>
```

**Comment by grapho** [comment]
is a component scoped helper more valuable/useful than a regular helper? maybe for addon developers?  it seems a regular computed property could achieve this too?

**Comment by jalcine** [comment]
[**@grapho**](https://github.com/grapho) commented on [Sep 9, 2015, 5:09 PM EDT](https://github.com/emberjs/rfcs/issues/89#issuecomment-139046552 "2015-09-09T21:09:08Z - Replied by Github Comment Enhancer"):
> is a component scoped helper more valuable/useful than a regular helper? maybe for addon developers?  it seems a regular computed property could achieve this too?

Scoping the helper makes more sense in terms of keeping the global helper collection clean and preventing breakage in the term a helper's removed from a component in the future.

**Comment by mfpiccolo** [comment]
I think it makes sense to scope helpers to components and allow them to be inherited.  There have been several times where I wanted to define a helper that only makes sense in a specific component or a group of components.  

I tried using a computed property but could not seem to figure out how to pass arguments to the functions that were available in the hbars templates.

@grapho @jalcine

**Comment by Panman8201** [comment]
This would be great for those instances where I need a Helper in one or two areas but don't want to pollute the global helpers space. Mainly, when looping over models in an `{{each}}` and needed a computed property per-model. I typically put the CP on the Model then, rather than making a lot of little "global" Helpers.

Another option could be to create something similar to `Ember.inject` and `Ember.computed` instead of using a `helpers:{}` hash. Maybe even make the current `Ember.Helper.helper()` work in a Component.

```javascript
// app/components/some-component.js
import Ember from 'ember';
export default Ember.Component.extend({
  atify: Ember.Helper.helper(function(params, hash){
  	return params[0].replace('a', '@');
  })
});
```

```handlebars
{{!-- app/templates/components/some-component.hbs --}}
<div>{{atify "Crazy"}}</div>
```

And just to clarify, this would only be available in the components template, unless `{{yield atify}}`'ed, correct? Also, if there was a global 'atify' helper, the component helper would take priority, override?

**Comment by mfpiccolo** [comment]
@Panman8201 That is not a bad idea.  Another idea would be to call a helper method on the function like property.  This would also allow options to be passed in like `{bound: true}`

```javascript
// app/components/some-component.js
import Ember from 'ember';
export default Ember.Component.extend({
  atify: function(params, hash){
    return params[0].replace('a', '@');
  }).helper(),
});
```

Yes, I think that if `atify` is defined globally the component should take priority.  Perhaps allow for `this._super()`.

Not sure what you mean by `{{yield atify}}`'ed.

**Comment by stefanpenner** [comment]
related: https://github.com/emberjs/rfcs/commit/7c43fb49b98e2e1c7f26a97f9d0475f8db8a089e

**Comment by Panman8201** [comment]
@mfpiccolo When using the component, can the "component helper" be used inside the block. Eg:

```handlebars
{{!-- app/templates/foo-bar.hbs --}}
{{#some-component as |atify|}}
   <p>{{atify "Crazy"}}</p>
{{/some-component}}
```

```handlebars
{{!-- app/templates/component/some-component.hbs --}}
{{yield atify}}
```

Now typing that out, I'm not sure that would work. Might need some sort of helper-helper?? Similar to the component helper, `{{component "component-name"}}`.

```handlebars
{{!-- app/templates/foo-bar.hbs --}}
{{#some-component as |atify|}}
   <p>{{helper atify "Crazy"}}</p>
{{/some-component}}
```

**Comment by mfpiccolo** [comment]
Mind :boom: 

I had not thought of that situation.  That does complicate things a bit.

**Comment by ming-codes** [comment]
> grapho commented on Sep 9, 2015
> is a component scoped helper more valuable/useful than a regular helper? maybe for addon developers? it seems a regular computed property could achieve this too?

Computed properties are not composeable. But you can compose computed properties with helpers. In which case, we do need something like component scoped helper.

I think what will make this even better is to allow the helper able to access (or even bind to) properties on the host component.

**Comment by rwjblue** [comment]
It is possible for a component (or route template) to have its own local helpers as of 2.5.0 (when used with a custom resolver). This feature is called "local lookup". See the modules normalization RFC for details. Once that RFC is finalized, a custom resolver will no longer be needed.

**Comment by locks** [comment]
With the [module unification RFC](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md) officially merged, I think we're in good shape to address this issue through local lookups!

**Comment by sandstrom** [comment]
This may actually be possible now (since Ember 3.27). More details: https://github.com/emberjs/rfcs/blob/master/text/0432-contextual-helpers.md#local-helpers-and-modifiers
