### ISSUE TITLE
Run Prettier separately in `app` blueprint

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs#901]
We could add two new scripts in the `package.json` file of the `app` blueprint:

```diff
+ "lint:format": "prettier . --cache --check",
+ "lint:format:fix": "prettier . --cache --write",
```

- `lint:format` would check the formatting of _all files_ Prettier supports
- `lint:format` would also run when running the `lint` script
- `lint:format:fix` would format _all files_ Prettier supports

It would also allow us to remove the following packages from the `app` blueprint:

```diff
- "eslint-config-prettier": "^8.6.0",
- "eslint-plugin-prettier": "^4.2.1",
- "stylelint-config-prettier": "^9.0.4",
- "stylelint-prettier": "^2.0.0",
```

But depends on the stylistic rules you have enabled / that are enabled by default for those linters. 

Later on, we could even add `prettier-plugin-ember-template-tag`, when template-imports support is included by default?

I think this would also (partially) cover https://github.com/emberjs/rfcs/issues/777?

Thoughts?

**Comment by NullVoxPopuli** [comment]
I'm a fan. It turns out that the prettier integratios for eslint is really slow.
Also, some folks _manually_ deal with red squigglies in their editor (even despite knowing about the format document command, or running eslint on save), so removing those would be a productivity boost for them.

**Comment by kellyselden** [comment]
Wouldn't it be something like "format" and "format:fix" to match the other conventions?

**Comment by NullVoxPopuli** [comment]
why learn extra CLI commands?

**Comment by kellyselden** [comment]
> why learn extra CLI commands?

What are you referring to? I'm referring to out existing conventions of using ":fix" to do code changes https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L18.

**Comment by bertdeblock** [comment]
The script names are probably not ideal at the moment, other suggestions are certainly welcome!
I mainly wanted the Prettier check to automatically be picked up when running `npm run lint`, hence `lint:format`.
And now that I think about it, it should probably be `lint:format:fix`, for it to be picked up by `lint:fix`.

**Comment by rwjblue** [comment]
RE: script names, I personally like `lint:prettier` and `lint:prettier:fix` for the two scripts. It plays well with the other top level scripts that we use `lint` and `lint:fix`.

**Comment by rwjblue** [comment]
It should also use `--ignore-unknown` IMO. This is what I tend to use:

```json
    "lint:prettier": "prettier --cache --ignore-unknown --check .",
    "lint:prettier:fix": "prettier --cache --write --ignore-unknown ."
```

**Comment by wagenet** [comment]
I do something very similar in the apps I work on, so I'm completely on board with this.

**Comment by bertdeblock** [comment]
Updated the `format` script to `lint:format:fix` in my initial comment.
Though, I have no strong preference between `lint:format:*` and `lint:prettier:*`.
I like that `lint:format:*` is more agnostic of the used tool, but `lint:prettier:*` is probably more clear.
