### ISSUE TITLE
New API for Component Focus Management

### ISSUE THREAD

**Issue by whastings** [emberjs/rfcs#93]
I'm interested in proposing that new methods be added to Ember.Component to facilitate focus management for improving the accessibility of Ember apps. I envision the following new methods:

* `focus()`: Sets focus to an element immediately. Takes an optional `child` argument. `child` will default to the selector specified in a new component property called `focusNode`. An arbitrary selector string, DOM element, or jQuery-wrapped element can also be passed for `child`. If no `child` is passed and `focusNode` is missing or falsey, the component's top-level element (`component.$()`) will be the element that receives focus.
* `focusAfterRender()`: Functions just like `focus()`, but uses the Run Loop to delay focusing until after the next rendering cycle. Useful for when the element to focus is not yet on the page.

I've written an initial implementation that I use in my practice Ember app to support screen reader users. It consists of the following:

* [An Ember.Component monkey patch][monkey_patch] that adds the methods described above.
* [A FocusManager service][service] that does the actual focusing work and ensures that only one element is focused per run of the after render queue.

Here are some examples of utilizing the new API:

* [Example 1][ex1]
* [Example 2][ex2]

The biggest outstanding question I have right now is how a parent component can trigger focus of a child component, given that parents generally do not have references to their children. In my app, I'm currently calling `focusAfterRender()` in the parent, but passing in the child's selector.

Before I try to take this further, I'd like to know: is this new API a good candidate for an Ember RFC and for addition to Ember core?

[monkey_patch]: https://github.com/whastings/ember-todo-app/blob/master/app/monkeypatches/component_focus_management.js
[service]: https://github.com/whastings/ember-todo-app/blob/master/app/services/focus-manager.js
[ex1]: https://github.com/whastings/ember-todo-app/blob/master/app/components/todo-list-app.js#L52
[ex2]: https://github.com/whastings/ember-todo-app/blob/master/app/components/todo-list-app.js#L23

**Comment by stefanpenner** [comment]
At the very least, would make a good add-on.

**Comment by whastings** [comment]
I finally got around to publishing this api in an add-on:
https://github.com/linkedin/ember-component-focus
